import type { SageDef } from "./types";

export const SAGES: SageDef[] = [
  {
    id: "al_idrissi",
    name: "Al-Idrissi",
    title: "Cartographe du monde", titleAr: "رسّام خريطة العالم",
    locationId: "fes",
    specialty: "Géographie & Cartographie",
    personality: "méthodique et contemplatif",
    portrait: "al_idrissi",
    dialogueIntro: "Ah, un voyageur qui cherche sa route ! Je suis Al-Idrissi, et j'ai cartographié le monde entier sur un disque d'argent pour le roi Roger II de Sicile. Avant d'entrer dans ma médersa, prouve-moi que tu mérites de naviguer dans les eaux du savoir…",
    dialogueIntroAr: "آه، مسافر يبحث عن طريقه! أنا الإدريسي، رسمت العالم كله على قرص من الفضة للملك روجر الثاني. قبل أن تدخل مدرستي، أثبت لي أنك تستحق الإبحار في بحار المعرفة…",
    dialogueSuccess: "Excellent ! Tu as la boussole du cœur et la carte de l'esprit. La Méditerranée ne te retient plus — file vers Cordoue, où le sage Ibn Rushd t'attend.",
    dialogueSuccessAr: "ممتاز! لديك بوصلة القلب وخريطة العقل. البحر الأبيض لم يعد يحجزك — انطلق نحو قرطبة حيث ينتظرك الحكيم ابن رشد.",
    dialogueFailure: "Les étoiles ne te guident pas encore assez bien, ami voyageur. Retourne étudier, et reviens. La connaissance n'est pas une destination — c'est un chemin.",
    dialogueFailureAr: "النجوم لا تهديك بعد بما يكفي، أيها المسافر. عد للدراسة وارجع. المعرفة ليست وجهة — إنها طريق يُستأنف دائماً.",
    reward: { xp: 200, coins: 50 },
    victoryRequirement: 7,
  },
  {
    id: "ibn_rushd",
    name: "Ibn Rushd",
    title: "Philosophe d'Andalousie", titleAr: "فيلسوف الأندلس",
    locationId: "cordoue",
    specialty: "Philosophie & Médecine",
    personality: "rigoureux et provocateur",
    portrait: "ibn_rushd",
    dialogueIntro: "Aristote a été oublié en Europe — c'est grâce à mes traductions en arabe qu'il a survécu. Je suis Ibn Rushd, Averroès pour les Latins. La raison et la foi ne s'opposent pas : elles s'éclairent.",
    dialogueIntroAr: "نُسي أرسطو في أوروبا — لكنه بقي بفضل ترجماتي إلى العربية. أنا ابن رشد. العقل والإيمان لا يتعارضان بل يتكاملان. لنثبت ذلك بإجاباتك.",
    dialogueSuccess: "Tu raisonnes avec la clarté d'un philosophe ! La Mosquée-Cathédrale de Cordoue témoignera de ta sagesse. Cap sur Marrakech.",
    dialogueSuccessAr: "تفكّر بوضوح الفلاسفة! مسجد قرطبة سيشهد على حكمتك. اتجه الآن نحو مراكش.",
    dialogueFailure: "La raison a besoin d'exercice, comme le muscle. Aristote lui-même a mis du temps. Reviens après avoir étudié.",
    dialogueFailureAr: "العقل يحتاج إلى تمرين كالعضلة. حتى أرسطو احتاج وقتاً. ارجع بعد الدراسة.",
    reward: { xp: 300, coins: 75 },
    victoryRequirement: 7,
  },
  {
    id: "ibn_toumert",
    name: "Ibn Toumert",
    title: "Fondateur des Almohades", titleAr: "مؤسس الموحدين",
    locationId: "marrakech",
    specialty: "Jurisprudence & Réforme",
    personality: "ferme et inspirant",
    portrait: "ibn_toumert",
    dialogueIntro: "J'ai traversé le désert pour ramener la vérité à mon peuple. Je suis Ibn Toumert, et la Koutoubia que tu vois fut érigée dans l'élan de ma réforme. Montre-moi la solidité de ton savoir.",
    dialogueIntroAr: "عبرتُ الصحراء لأعيد الحق لشعبي. أنا ابن تومرت، والكتبية التي تراها قامت في موجة إصلاحي. أرِني متانة علمك.",
    dialogueSuccess: "Tu as la fermeté du Haut-Atlas ! La cité ocre t'ouvre ses portes. Damas est la prochaine étape.",
    dialogueSuccessAr: "لديك صلابة جبال الأطلس الكبير! المدينة الحمراء تفتح لك أبوابها. دمشق هي محطتك القادمة.",
    dialogueFailure: "Même les montagnes ont été façonnées par le temps. Persévère, et tu trouveras ta forme.",
    dialogueFailureAr: "حتى الجبال نحتها الزمن. اصبر وستجد شكلك.",
    reward: { xp: 450, coins: 100 },
    victoryRequirement: 7,
  },
  {
    id: "ibn_asaker",
    name: "Ibn Asaker",
    title: "Historien de Damas", titleAr: "مؤرّخ دمشق",
    locationId: "damas",
    specialty: "Histoire & Biographies",
    personality: "patient et exhaustif",
    portrait: "ibn_asaker",
    dialogueIntro: "J'ai consacré ma vie à ne rien oublier : j'ai compilé 1300 biographies de compagnons et de savants. Je suis Ibn Asaker. La mémoire est le trésor des nations.",
    dialogueIntroAr: "كرّستُ حياتي لأن لا أنسى شيئاً: جمعتُ 1300 سيرة للصحابة والعلماء. أنا ابن عساكر. الذاكرة كنز الأمم. انظر هل ذاكرتك تليق بدمشق.",
    dialogueSuccess: "Ta mémoire est précieuse comme un manuscrit rare ! L'histoire t'appartient. Bagdad et Al-Khwarizmi t'attendent.",
    dialogueSuccessAr: "ذاكرتك ثمينة كمخطوطة نادرة! التاريخ أصبح ملكك. بغداد والخوارزمي ينتظرانك.",
    dialogueFailure: "Même mon encyclopédie de 80 volumes a pris 60 ans. La patience est la première vertu de l'historien.",
    dialogueFailureAr: "حتى موسوعتي من 80 مجلداً استغرقت 60 عاماً. الصبر أول فضائل المؤرخ.",
    reward: { xp: 600, coins: 130 },
    victoryRequirement: 7,
  },
  {
    id: "al_khwarizmi",
    name: "Al-Khwarizmi",
    title: "Père de l'algèbre", titleAr: "أبو الجبر",
    locationId: "bagdad",
    specialty: "Mathématiques & Astronomie",
    personality: "précis et méthodique",
    portrait: "al_khwarizmi",
    dialogueIntro: "Mon nom a donné le mot 'algorithme' et mon traité a donné 'algèbre' — al-jabr. Je suis Al-Khwarizmi, et la Maison de la Sagesse est mon atelier. Les nombres ont une logique implacable.",
    dialogueIntroAr: "اسمي أعطى كلمة 'خوارزمية' وكتابي أعطى 'الجبر' — الجبر. أنا الخوارزمي، وبيت الحكمة مشغلي. للأرقام منطق لا يُقهر. لنرَ هل تستطيع اتباعه.",
    dialogueSuccess: "Parfait ! Tu calcules comme un astronome de Bagdad. Les routes de la soie mènent à Samarcande.",
    dialogueSuccessAr: "ممتاز! تحسب كفلكي بغداد. طرق الحرير تقودك الآن إلى سمرقند.",
    dialogueFailure: "L'équation est simple : connaissance = effort × temps. Reviens !",
    dialogueFailureAr: "المعادلة بسيطة: المعرفة = الجهد × الوقت. ارجع!",
    reward: { xp: 800, coins: 165 },
    victoryRequirement: 7,
  },
  {
    id: "ibn_sina",
    name: "Ibn Sina",
    title: "Prince des médecins", titleAr: "أمير الأطباء",
    locationId: "samarcande",
    specialty: "Médecine & Philosophie",
    personality: "brillant et polyvalent",
    portrait: "ibn_sina",
    dialogueIntro: "J'ai écrit le Canon de la médecine à 21 ans. Avicenne, m'appellent les Latins. À Samarcande, carrefour du monde, je t'invite à mesurer l'étendue de ton savoir.",
    dialogueIntroAr: "كتبتُ القانون في الطب وعمري 21 عاماً. في سمرقند، ملتقى العالم، أدعوك لقياس مدى علمك. الجسد والروح والكون — كل شيء مترابط.",
    dialogueSuccess: "Ton esprit est sain et ton savoir florissant ! Les caravanes du Mali t'attendent à Tombouctou.",
    dialogueSuccessAr: "عقلك سليم وعلمك مزدهر! قوافل مالي تنتظرك في تمبكتو.",
    dialogueFailure: "Un médecin qui ne connaît pas ses limites est dangereux. Étudie, puis reviens.",
    dialogueFailureAr: "طبيب لا يعرف حدوده خطر. ادرس ثم ارجع شافياً من جهلك.",
    reward: { xp: 1000, coins: 200 },
    victoryRequirement: 7,
  },
  {
    id: "ahmad_baba",
    name: "Ahmad Baba",
    title: "Gardien des manuscrits", titleAr: "حارس المخطوطات",
    locationId: "tombouctou",
    specialty: "Lettres & Jurisprudence",
    personality: "passionné et défenseur de la dignité humaine",
    portrait: "ahmad_baba",
    dialogueIntro: "Tombouctou n'est pas le bout du monde — c'est son centre ! J'ai réuni jusqu'à 700 000 manuscrits ici. Je suis Ahmad Baba, et j'ai lutté contre l'esclavage avec ma plume.",
    dialogueIntroAr: "تمبكتو ليست نهاية العالم — بل مركزه! جمعتُ هنا حتى 700 ألف مخطوطة. أنا أحمد بابا، وناضلتُ ضد العبودية بقلمي. أرِني أن المعرفة الأفريقية مألوفة لك.",
    dialogueSuccess: "Magnifique ! Tu portes la lumière de Tombouctou en toi. Le Caire et Ibn Khaldoun t'y attendent.",
    dialogueSuccessAr: "رائع! تحمل نور تمبكتو في داخلك. القاهرة وابن خلدون ينتظرانك.",
    dialogueFailure: "Les manuscrits de Tombouctou ont survécu aux invasions. Ta curiosité survivra à cet échec. Reviens !",
    dialogueFailureAr: "صمدت مخطوطات تمبكتو أمام الغزوات. فضولك سيصمد أمام هذا الفشل. ارجع!",
    reward: { xp: 1200, coins: 240 },
    victoryRequirement: 7,
  },
  {
    id: "ibn_khaldoun",
    name: "Ibn Khaldoun",
    title: "Père de la sociologie", titleAr: "أبو علم الاجتماع",
    locationId: "le_caire",
    specialty: "Sociologie & Histoire",
    personality: "analytique et visionnaire",
    portrait: "ibn_khaldoun",
    dialogueIntro: "J'ai compris avant tout le monde que les sociétés naissent, prospèrent et déclinent selon des lois précises. Je suis Ibn Khaldoun, et ma Muqaddima est le premier traité de sciences sociales de l'histoire.",
    dialogueIntroAr: "فهمتُ قبل الجميع أن المجتمعات تنشأ وتزدهر وتنحدر وفق قوانين دقيقة. أنا ابن خلدون، ومقدمتي أول رسالة في علوم الاجتماع في التاريخ. أثبت أنك تفهم العالم.",
    dialogueSuccess: "Tu as l'œil d'un sociologue et l'âme d'un historien ! La Mecque est à portée — le sommet t'attend.",
    dialogueSuccessAr: "لديك عين عالم الاجتماع وروح المؤرخ! مكة في متناول يدك — قمة رحلتك تنتظر.",
    dialogueFailure: "Toute civilisation a ses hauts et ses bas. Ton savoir aussi. Reviens quand il sera au zénith.",
    dialogueFailureAr: "لكل حضارة صعود وهبوط. علمك كذلك. ارجع حين يبلغ ذروته.",
    reward: { xp: 1500, coins: 300 },
    victoryRequirement: 7,
  },
];

export function getSage(id: string): SageDef | undefined {
  return SAGES.find(s => s.id === id);
}

export function getSageForLocation(locationId: string): SageDef | undefined {
  return SAGES.find(s => s.locationId === locationId);
}
