import type { SageDef } from "./types";

export const SAGES: SageDef[] = [
  {
    id: "al_idrissi",
    name: "Al-Idrissi",
    title: "Cartographe du monde", titleAr: "رسّام خريطة العالم",
    locationId: "fes",
    specialty: "Géographie & Cartographie",
    personality: "méthodique et contemplatif",
    portrait: "al_idrissi",
    dialogueIntro: "Ah, un voyageur qui cherche sa route ! Je suis Al-Idrissi, et j'ai cartographié le monde entier sur un disque d'argent pour le roi Roger II de Sicile. Avant d'entrer dans ma médersa, prouve-moi que tu mérites de naviguer dans les eaux du savoir…",
    dialogueIntroAr: "آه، مسافر يبحث عن طريقه! أنا الإدريسي، رسمت العالم كله على قرص من الفضة للملك روجر الثاني. قبل أن تدخل مدرستي، أثبت لي أنك تستحق الإبحار في بحار المعرفة…",
    dialogueSuccess: "Excellent ! Tu as la boussole du cœur et la carte de l'esprit. La Méditerranée ne te retient plus — file vers Cordoue, où le sage Ibn Rushd t'attend.",
    dialogueSuccessAr: "ممتاز! لديك بوصلة القلب وخريطة العقل. البحر الأبيض لم يعد يحجزك — انطلق نحو قرطبة حيث ينتظرك الحكيم ابن رشد.",
    dialogueFailure: "Les étoiles ne te guident pas encore assez bien, ami voyageur. Retourne étudier, et reviens. La connaissance n'est pas une destination — c'est un chemin.",
    dialogueFailureAr: "النجوم لا تهديك بعد بما يكفي، أيها المسافر. عد للدراسة وارجع. المعرفة ليست وجهة — إنها طريق يُستأنف دائماً.",
    reward: { xp: 200, coins: 50 },
    victoryRequirement: 7,
  },
  {
    id: "ibn_rushd",
    name: "Ibn Rushd",
    title: "Philosophe d'Andalousie", titleAr: "فيلسوف الأندلس",
    locationId: "cordoue",
    specialty: "Philosophie & Médecine",
    personality: "rigoureux et provocateur",
    portrait: "ibn_rushd",
    dialogueIntro: "Aristote a été oublié en Europe — c'est grâce à mes traductions en arabe qu'il a survécu. Je suis Ibn Rushd, Averroès pour les Latins. La raison et la foi ne s'opposent pas : elles s'éclairent.",
    dialogueIntroAr: "نُسي أرسطو في أوروبا — لكنه بقي بفضل ترجماتي إلى العربية. أنا ابن رشد. العقل والإيمان لا يتعارضان بل يتكاملان. لنثبت ذلك بإجاباتك.",
    dialogueSuccess: "Tu raisonnes avec la clarté d'un philosophe ! La Mosquée-Cathédrale de Cordoue témoignera de ta sagesse. Cap sur Marrakech.",
    dialogueSuccessAr: "تفكّر بوضوح الفلاسفة! مسجد قرطبة سيشهد على حكمتك. اتجه الآن نحو مراكش.",
    dialogueFailure: "La raison a besoin d'exercice, comme le muscle. Aristote lui-même a mis du temps. Reviens après avoir étudié.",
    dialogueFailureAr: "العقل يحتاج إلى تمرين كالعضلة. حتى أرسطو احتاج وقتاً. ارجع بعد الدراسة.",
    reward: { xp: 300, coins: 75 },
    victoryRequirement: 7,
  },
  {
    id: "ibn_toumert",
    name: "Ibn Toumert",
    title: "Fondateur des Almohades", titleAr: "مؤسس الموحدين",
    locationId: "marrakech",
    specialty: "Jurisprudence & Réforme",
    personality: "ferme et inspirant",
    portrait: "ibn_toumert",
    dialogueIntro: "J'ai traversé le désert pour ramener la vérité à mon peuple. Je suis Ibn Toumert, et la Koutoubia que tu vois fut érigée dans l'élan de ma réforme. Montre-moi la solidité de ton savoir.",
    dialogueIntroAr: "عبرتُ الصحراء لأعيد الحق لشعبي. أنا ابن تومرت، والكتبية التي تراها قامت في موجة إصلاحي. أرِني متانة علمك.",
    dialogueSuccess: "Tu as la fermeté du Haut-Atlas ! La cité ocre t'ouvre ses portes. Damas est la prochaine étape.",
    dialogueSuccessAr: "لديك صلابة جبال الأطلس الكبير! المدينة الحمراء تفتح لك أبوابها. دمشق هي محطتك القادمة.",
    dialogueFailure: "Même les montagnes ont été façonnées par le temps. Persévère, et tu trouveras ta forme.",
    dialogueFailureAr: "حتى الجبال نحتها الزمن. اصبر وستجد شكلك.",
    reward: { xp: 450, coins: 100 },
    victoryRequirement: 8,
  },
  {
    id: "ibn_asaker",
    name: "Ibn Asaker",
    title: "Historien de Damas", titleAr: "مؤرّخ دمشق",
    locationId: "damas",
    specialty: "Histoire & Biographies",
    personality: "patient et exhaustif",
    portrait: "ibn_asaker",
    dialogueIntro: "J'ai consacré ma vie à ne rien oublier : j'ai compilé 1300 biographies de compagnons et de savants. Je suis Ibn Asaker. La mémoire est le trésor des nations.",
    dialogueIntroAr: "كرّستُ حياتي لأن لا أنسى شيئاً: جمعتُ 1300 سيرة للصحابة والعلماء. أنا ابن عساكر. الذاكرة كنز الأمم. انظر هل ذاكرتك تليق بدمشق.",
    dialogueSuccess: "Ta mémoire est précieuse comme un manuscrit rare ! L'histoire t'appartient. Bagdad et Al-Khwarizmi t'attendent.",
    dialogueSuccessAr: "ذاكرتك ثمينة كمخطوطة نادرة! التاريخ أصبح ملكك. بغداد والخوارزمي ينتظرانك.",
    dialogueFailure: "Même mon encyclopédie de 80 volumes a pris 60 ans. La patience est la première vertu de l'historien.",
    dialogueFailureAr: "حتى موسوعتي من 80 مجلداً استغرقت 60 عاماً. الصبر أول فضائل المؤرخ.",
    reward: { xp: 600, coins: 130 },
    victoryRequirement: 8,
  },
  {
    id: "al_khwarizmi",
    name: "Al-Khwarizmi",
    title: "Père de l'algèbre", titleAr: "أبو الجبر",
    locationId: "bagdad",
    specialty: "Mathématiques & Astronomie",
    personality: "précis et méthodique",
    portrait: "al_khwarizmi",
    dialogueIntro: "Mon nom a donné le mot 'algorithme' et mon traité a donné 'algèbre' — al-jabr. Je suis Al-Khwarizmi, et la Maison de la Sagesse est mon atelier. Les nombres ont une logique implacable.",
    dialogueIntroAr: "اسمي أعطى كلمة 'خوارزمية' وكتابي أعطى 'الجبر' — الجبر. أنا الخوارزمي، وبيت الحكمة مشغلي. للأرقام منطق لا يُقهر. لنرَ هل تستطيع اتباعه.",
    dialogueSuccess: "Parfait ! Tu calcules comme un astronome de Bagdad. Les routes de la soie mènent à Samarcande.",
    dialogueSuccessAr: "ممتاز! تحسب كفلكي بغداد. طرق الحرير تقودك الآن إلى سمرقند.",
    dialogueFailure: "L'équation est simple : connaissance = effort × temps. Reviens !",
    dialogueFailureAr: "المعادلة بسيطة: المعرفة = الجهد × الوقت. ارجع!",
    reward: { xp: 800, coins: 165 },
    victoryRequirement: 8,
  },
  {
    id: "ibn_sina",
    name: "Ibn Sina",
    title: "Prince des médecins", titleAr: "أمير الأطباء",
    locationId: "samarcande",
    specialty: "Médecine & Philosophie",
    personality: "brillant et polyvalent",
    portrait: "ibn_sina",
    dialogueIntro: "J'ai écrit le Canon de la médecine à 21 ans. Avicenne, m'appellent les Latins. À Samarcande, carrefour du monde, je t'invite à mesurer l'étendue de ton savoir.",
    dialogueIntroAr: "كتبتُ القانون في الطب وعمري 21 عاماً. في سمرقند، ملتقى العالم، أدعوك لقياس مدى علمك. الجسد والروح والكون — كل شيء مترابط.",
    dialogueSuccess: "Ton esprit est sain et ton savoir florissant ! Les caravanes du Mali t'attendent à Tombouctou.",
    dialogueSuccessAr: "عقلك سليم وعلمك مزدهر! قوافل مالي تنتظرك في تمبكتو.",
    dialogueFailure: "Un médecin qui ne connaît pas ses limites est dangereux. Étudie, puis reviens.",
    dialogueFailureAr: "طبيب لا يعرف حدوده خطر. ادرس ثم ارجع شافياً من جهلك.",
    reward: { xp: 1000, coins: 200 },
    victoryRequirement: 9,
  },
  {
    id: "ahmad_baba",
    name: "Ahmad Baba",
    title: "Gardien des manuscrits", titleAr: "حارس المخطوطات",
    locationId: "tombouctou",
    specialty: "Lettres & Jurisprudence",
    personality: "passionné et défenseur de la dignité humaine",
    portrait: "ahmad_baba",
    dialogueIntro: "Tombouctou n'est pas le bout du monde — c'est son centre ! J'ai réuni jusqu'à 700 000 manuscrits ici. Je suis Ahmad Baba, et j'ai lutté contre l'esclavage avec ma plume.",
    dialogueIntroAr: "تمبكتو ليست نهاية العالم — بل مركزه! جمعتُ هنا حتى 700 ألف مخطوطة. أنا أحمد بابا، وناضلتُ ضد العبودية بقلمي. أرِني أن المعرفة الأفريقية مألوفة لك.",
    dialogueSuccess: "Magnifique ! Tu portes la lumière de Tombouctou en toi. Le Caire et Ibn Khaldoun t'y attendent.",
    dialogueSuccessAr: "رائع! تحمل نور تمبكتو في داخلك. القاهرة وابن خلدون ينتظرانك.",
    dialogueFailure: "Les manuscrits de Tombouctou ont survécu aux invasions. Ta curiosité survivra à cet échec. Reviens !",
    dialogueFailureAr: "صمدت مخطوطات تمبكتو أمام الغزوات. فضولك سيصمد أمام هذا الفشل. ارجع!",
    reward: { xp: 1200, coins: 240 },
    victoryRequirement: 9,
  },
  {
    id: "ibn_khaldoun",
    name: "Ibn Khaldoun",
    title: "Père de la sociologie", titleAr: "أبو علم الاجتماع",
    locationId: "le_caire",
    specialty: "Sociologie & Histoire",
    personality: "analytique et visionnaire",
    portrait: "ibn_khaldoun",
    dialogueIntro: "J'ai compris avant tout le monde que les sociétés naissent, prospèrent et déclinent selon des lois précises. Je suis Ibn Khaldoun, et ma Muqaddima est le premier traité de sciences sociales de l'histoire.",
    dialogueIntroAr: "فهمتُ قبل الجميع أن المجتمعات تنشأ وتزدهر وتنحدر وفق قوانين دقيقة. أنا ابن خلدون، ومقدمتي أول رسالة في علوم الاجتماع في التاريخ. أثبت أنك تفهم العالم.",
    dialogueSuccess: "Tu as l'œil d'un sociologue et l'âme d'un historien ! La Mecque est à portée — le sommet t'attend.",
    dialogueSuccessAr: "لديك عين عالم الاجتماع وروح المؤرخ! مكة في متناول يدك — قمة رحلتك تنتظر.",
    dialogueFailure: "Toute civilisation a ses hauts et ses bas. Ton savoir aussi. Reviens quand il sera au zénith.",
    dialogueFailureAr: "لكل حضارة صعود وهبوط. علمك كذلك. ارجع حين يبلغ ذروته.",
    reward: { xp: 1500, coins: 300 },
    victoryRequirement: 9,
  },
];

// ── ÈRE II SAGES ────────────────────────────────────────────────
SAGES.push(
  {
    id: "al_negus",
    name: "Al-Negus",
    title: "Roi juste d'Abyssinie", titleAr: "الملك العادل في أكسوم",
    locationId: "abyssinie",
    specialty: "Justice & Hospitalité",
    personality: "sage et équitable",
    portrait: "al_idrissi", // fallback portrait
    dialogueIntro: "Je suis Ashama ibn Abjar, le Negus d'Abyssinie. Quand les musulmans fuyaient la persécution à La Mecque, je leur ai offert refuge. Je ne rends pas un homme à ceux qui l'oppriment. Prouve-moi que tu mérites de connaître cette histoire.",
    dialogueIntroAr: "أنا أشمة بن أبجر، نجاشي الحبشة. حين فرّ المسلمون من اضطهاد مكة، أعطيتهم ملاذاً. لا أسلّم إنساناً لمن يظلمه. أثبت لي أنك تستحق معرفة هذه القصة.",
    dialogueSuccess: "Tu as la noblesse du savoir ! Je me suis converti en secret à l'islam en entendant la Sourate Maryam récitée par Ja'far ibn Abi Talib. Continue vers Jérusalem.",
    dialogueSuccessAr: "لديك نبل المعرفة! أسلمتُ سراً حين سمعت سورة مريم من جعفر بن أبي طالب. واصل نحو القدس.",
    dialogueFailure: "La justice ne s'improvise pas. Reviens étudier cette période bénie.",
    dialogueFailureAr: "العدل لا يُرتجل. ارجع وادرس هذه المرحلة المباركة.",
    reward: { xp: 400, coins: 80 },
    victoryRequirement: 7,
  },
  {
    id: "bilal",
    name: "Bilal ibn Rabah",
    title: "Premier muezzin de l'islam", titleAr: "أول مؤذن في الإسلام",
    locationId: "jerusalem",
    specialty: "Appel à la prière & Résistance",
    personality: "inébranlable et mélodieux",
    portrait: "ibn_asaker", // fallback portrait
    dialogueIntro: "Je suis Bilal ibn Rabah. Esclave abyssinien, torturé pour ma foi, libéré par Abu Bakr. Le Prophète ﷺ m'a choisi pour être la première voix de l'adhan depuis Al-Aqsa. Ahad, ahad — un seul Dieu. C'est tout ce que j'avais à dire sous la torture.",
    dialogueIntroAr: "أنا بلال بن رباح. عبدٌ حبشي عُذِّب على إيمانه، أعتقه أبو بكر. اختارني النبي ﷺ لأكون أول صوت للأذان من الأقصى. أحد، أحد — ذلك كل ما كنت أقوله تحت التعذيب.",
    dialogueSuccess: "Ta voix résonne avec la vérité ! Isra' wal Mi'raj — la nuit où le Prophète ﷺ monta vers Allah depuis ici même. Continue à Taïf.",
    dialogueSuccessAr: "صوتك يرنّ بالحق! الإسراء والمعراج — الليلة التي عرج فيها النبي ﷺ إلى الله من هنا ذاتها.",
    dialogueFailure: "Même sous le poids des rochers, Ahad. Reviens apprendre.",
    dialogueFailureAr: "حتى تحت ثقل الصخور، أحد. ارجع وتعلّم.",
    reward: { xp: 500, coins: 100 },
    victoryRequirement: 7,
  },
  {
    id: "salmane",
    name: "Salmane al-Farisi",
    title: "Le chercheur de vérité", titleAr: "طالب الحق",
    locationId: "taif",
    specialty: "Quête spirituelle & Stratégie",
    personality: "persévérant et ingénieux",
    portrait: "al_khwarizmi", // fallback portrait
    dialogueIntro: "Je suis Salmane al-Farisi. Né en Perse, j'ai quitté le zoroastrisme pour chercher la vérité. J'ai traversé des pays, servi des prêtres chrétiens, été vendu comme esclave — tout cela pour trouver le dernier prophète. Et il est là : Muhammad ﷺ. Pour la bataille de Khandak, c'est moi qui ai proposé de creuser le fossé.",
    dialogueIntroAr: "أنا سلمان الفارسي. وُلدتُ في فارس وتركتُ المجوسية باحثاً عن الحق. عبرتُ بلداناً وخدمتُ كهنة نصارى وبِعتُ عبداً — كل ذلك للعثور على النبي الأخير. وهو ها هو: محمد ﷺ. وفي غزوة الخندق، اقترحتُ حفر الخندق.",
    dialogueSuccess: "Salmane est de nous, ahl al-bayt ! Comme disait le Prophète ﷺ. Continue vers Médine.",
    dialogueSuccessAr: "سلمان منا أهل البيت! كما قال النبي ﷺ. واصل نحو المدينة.",
    dialogueFailure: "J'ai traversé la Perse, la Syrie et le Hedjaz pour la vérité. Un peu d'effort !",
    dialogueFailureAr: "عبرتُ فارس والشام والحجاز طلباً للحق. ابذل بعض الجهد!",
    reward: { xp: 650, coins: 120 },
    victoryRequirement: 8,
  },
  {
    id: "aisha",
    name: "Aïcha bint Abi Bakr",
    title: "Mère des croyants & Savante", titleAr: "أم المؤمنين والعالمة",
    locationId: "medine_hijra",
    specialty: "Hadith & Sciences islamiques",
    personality: "perspicace et directe",
    portrait: "ibn_rushd", // fallback portrait
    dialogueIntro: "Je suis Aïcha, fille d'Abu Bakr, épouse du Prophète ﷺ. 2 210 hadiths portent mon nom. Les Compagnons venaient à ma tente pour comprendre la sunna du Prophète ﷺ dans sa vie privée. On ne peut connaître l'islam complètement sans les femmes qui l'ont vécu.",
    dialogueIntroAr: "أنا عائشة بنت أبي بكر، زوج النبي ﷺ. 2210 حديثاً تحمل اسمي. كان الصحابة يأتون خيمتي ليفهموا سنة النبي ﷺ في حياته الخاصة. لا يمكن معرفة الإسلام كاملاً دون النساء اللواتي عشنه.",
    dialogueSuccess: "Excellent ! Comme disait Mu'adh ibn Jabal : 'Sachez que dès qu'Aïcha parle, les savants se taisent.' Avance vers Khaybar.",
    dialogueSuccessAr: "ممتاز! كما قال معاذ بن جبل: 'اعلموا أن عائشة إذا تكلمت سكت العلماء.' تقدم نحو خيبر.",
    dialogueFailure: "La connaissance est une obligation pour tout musulman et toute musulmane. Reviens studieux.",
    dialogueFailureAr: "طلب العلم فريضة على كل مسلم ومسلمة. ارجع ودارساً.",
    reward: { xp: 800, coins: 150 },
    victoryRequirement: 8,
  },
  {
    id: "saad_ibn_muadh",
    name: "Sa'd ibn Mu'adh",
    title: "Chef des Aws & Compagnon", titleAr: "سيد الأوس والصحابي",
    locationId: "khaybar",
    specialty: "Leadership & Batailles prophétiques",
    personality: "loyal et courageux",
    portrait: "ibn_toumert", // fallback portrait
    dialogueIntro: "Je suis Sa'd ibn Mu'adh, chef de la tribu des Aws à Médine. Je me suis converti à l'islam le même jour où Mus'ab ibn Umayr est arrivé à Médine comme enseignant. Lors de Khandak, c'est ma blessure qui a conduit le Prophète ﷺ à dire que le Trône divin a tremblé à ma mort.",
    dialogueIntroAr: "أنا سعد بن معاذ، سيد قبيلة الأوس في المدينة. أسلمتُ يوم قدم مصعب بن عمير معلماً للمدينة. في الخندق، قال النبي ﷺ عند وفاتي بسبب جرحي إن عرش الرحمن اهتز.",
    dialogueSuccess: "Tu as la bravoure du savoir ! 'Tout homme vertueux que nous connaissons, Sa'd le surpassait.' — dixit Abu Sa'id al-Khudri. La Mecque t'attend.",
    dialogueSuccessAr: "لديك شجاعة المعرفة! 'كل رجل فاضل نعرفه، كان سعد يتفوق عليه.' — قاله أبو سعيد الخدري. مكة تنتظرك.",
    dialogueFailure: "Les guerres prophétiques méritent une étude approfondie. Reviens.",
    dialogueFailureAr: "الغزوات النبوية تستحق دراسة معمّقة. ارجع.",
    reward: { xp: 1000, coins: 180 },
    victoryRequirement: 9,
  },
);

// ── ÈRE III SAGES ────────────────────────────────────────────────
SAGES.push(
  {
    id: "ibn_abi_zayd",
    name: "Ibn Abi Zayd al-Qayrawani",
    title: "Le petit Malik", titleAr: "مالك الصغير",
    locationId: "kairouan",
    specialty: "Jurisprudence malékite",
    personality: "rigoureux et encyclopédique",
    portrait: "al_idrissi",
    dialogueIntro: "Je suis Ibn Abi Zayd al-Qayrawani (922-996). À Kairouan, j'ai rédigé la Risala — un abrégé du fiqh malékite si complet qu'on m'a surnommé 'le petit Malik'. Les mosquées du Maghreb ont formé leurs imams avec mon texte depuis mille ans.",
    dialogueIntroAr: "أنا ابن أبي زيد القيرواني (922-996). في القيروان ألّفت الرسالة — ملخصاً للفقه المالكي اكتمل حتى سُمّيتُ 'مالك الصغير'. مساجد المغرب تخرّج أئمتها على نصّي منذ ألف عام.",
    dialogueSuccess: "Masha'Allah ! Tu as la rigueur d'un faqih. Alexandrie et ses savants t'attendent.",
    dialogueSuccessAr: "ما شاء الله! لديك دقة الفقيه. الإسكندرية وعلماؤها ينتظرونك.",
    dialogueFailure: "La jurisprudence est un océan. Reviens avec plus d'humilité et de préparation.",
    dialogueFailureAr: "الفقه بحر. ارجع بتواضع وإعداد أكبر.",
    reward: { xp: 700, coins: 130 },
    victoryRequirement: 8,
  },
  {
    id: "ibn_haytham",
    name: "Ibn al-Haytham",
    title: "Père de l'optique moderne", titleAr: "أبو البصريات الحديثة",
    locationId: "alexandrie",
    specialty: "Optique, physique & méthode scientifique",
    personality: "méthodique et expérimentateur",
    portrait: "al_khwarizmi",
    dialogueIntro: "Je suis Ibn al-Haytham (965-1040). On m'a dit à Bassora : 'Si seulement vous étiez en Égypte, vous pourriez réguler le Nil !' J'y suis allé, ai simulé la folie pour éviter l'exécution du calife fatimide, puis j'ai écrit le Kitab al-Manazir — 7 volumes sur la lumière et la vision qui ont révolutionné l'Europe 500 ans plus tard.",
    dialogueIntroAr: "أنا ابن الهيثم (965-1040). قيل لي في البصرة: 'لو كنتَ في مصر لضبطتَ النيل!' ذهبتُ، تظاهرتُ بالجنون لأنجو من بطش الخليفة الفاطمي، ثم كتبتُ كتاب المناظر — 7 مجلدات في الضوء والرؤية غيّرت أوروبا بعد 500 عام.",
    dialogueSuccess: "Excellent ! Tu observes avec les yeux du savant. Chiraz la poétique t'appelle.",
    dialogueSuccessAr: "ممتاز! تُراقب بعيون العالم. شيراز الشاعرة تناديك.",
    dialogueFailure: "Je suis resté 10 ans dans ma chambre plutôt que d'être exécuté. La patience s'impose.",
    dialogueFailureAr: "مكثتُ 10 سنوات في غرفتي بدلاً من الإعدام. الصبر ضرورة.",
    reward: { xp: 900, coins: 160 },
    victoryRequirement: 8,
  },
  {
    id: "hafez",
    name: "Hafez de Chiraz",
    title: "La langue du mystère", titleAr: "لسان الغيب",
    locationId: "chiraz",
    specialty: "Poésie soufie & littérature persane",
    personality: "mystique et profond",
    portrait: "ibn_rushd",
    dialogueIntro: "Je suis Shams ud-Din Muhammad Hafez (1315-1390). Mon Divan de 500 poèmes est le livre le plus récité en Iran après le Coran. Goethe m'a lu et a écrit son Divan occidental en réponse. 'Ne demande pas la raison de mon vin — c'est la coupe de Jamshid qui révèle les secrets du monde.'",
    dialogueIntroAr: "أنا شمس الدين محمد حافظ (1315-1390). ديواني من 500 قصيدة هو أكثر كتاب يُتلى في إيران بعد القرآن. قرأه غوته وكتب ديوانه الغربي-الشرقي رداً عليه. 'لا تسأل عن سبب خمري — هذه كأس جمشيد تكشف أسرار العالم.'",
    dialogueSuccess: "Ton âme résonne ! 'Même si tu restes cent ans, le jardin du monde sera comme aujourd'hui.' Continue à Tolède.",
    dialogueSuccessAr: "روحك ترنّ! 'حتى لو بقيتَ مئة عام، ستبقى حديقة العالم كما هي.' واصل نحو طليطلة.",
    dialogueFailure: "Le vin de la connaissance réclame patience. Reviens le cœur ouvert.",
    dialogueFailureAr: "خمر المعرفة تتطلب صبراً. ارجع بقلب مفتوح.",
    reward: { xp: 1100, coins: 190 },
    victoryRequirement: 8,
  },
  {
    id: "ibn_wafid",
    name: "Ibn Wafid de Tolède",
    title: "Médecin botaniste d'Al-Andalus", titleAr: "طبيب النبات الأندلسي",
    locationId: "tolede",
    specialty: "Médecine, botanique & transmission du savoir",
    personality: "polymathe et passeur de savoirs",
    portrait: "ibn_asaker",
    dialogueIntro: "Je suis Ibn Wafid (997-1074). À Tolède, j'ai soigné le roi, cultivé les jardins médicaux du palais, et j'ai compilé le premier traité de médications simples d'Al-Andalus. Après la chute de Tolède aux Chrétiens en 1085, c'est ici que nos manuscrits seront traduits en latin — Al-Kindi, Al-Farabi, Ibn Sina... L'Europe va apprendre.",
    dialogueIntroAr: "أنا ابن وافد (997-1074). في طليطلة داويتُ الملك وزرعتُ حدائق القصر الطبية وجمعتُ أول موسوعة أندلسية للأدوية المفردة. بعد سقوط طليطلة للمسيحيين عام 1085، هنا ستُترجم مخطوطاتنا للاتينية — الكندي والفارابي وابن سينا... ستتعلم أوروبا.",
    dialogueSuccess: "Magnifique passeur ! À Nishapur, Omar Khayyam t'attend avec ses équations et ses quatrains.",
    dialogueSuccessAr: "ناقل رائع! في نيسابور ينتظرك عمر الخيام بمعادلاته ورباعياته.",
    dialogueFailure: "La transmission du savoir est une responsabilité. Étudie avant de passer.",
    dialogueFailureAr: "نقل العلم مسؤولية. ادرس قبل أن تنقل.",
    reward: { xp: 1300, coins: 220 },
    victoryRequirement: 9,
  },
  {
    id: "omar_khayyam",
    name: "Omar Khayyam",
    title: "Mathématicien & Poète", titleAr: "الرياضي والشاعر",
    locationId: "nishapur",
    specialty: "Mathématiques, astronomie & Ruba'iyat",
    personality: "brillant, mélancolique et libre",
    portrait: "al_khwarizmi",
    dialogueIntro: "Je suis Omar Khayyam (1048-1131). J'ai résolu les équations cubiques par des sections coniques, réformé le calendrier perso-solaire (plus précis que le grégorien !) et composé les Ruba'iyat — 600 quatrains sur la vie, la mort et le vin de la sagesse. FitzGerald m'a traduit en anglais en 1859 et fait de moi le poète oriental le plus lu en Occident.",
    dialogueIntroAr: "أنا عمر الخيام (1048-1131). حللتُ المعادلات التكعيبية بالمقاطع المخروطية، وأصلحتُ التقويم الفارسي الشمسي (أدق من الغريغوري!)، ونظمتُ الرباعيات — 600 رباعية عن الحياة والموت وخمر الحكمة.",
    dialogueSuccess: "Tu penses comme un géomètre et sens comme un poète ! Le cercle de l'Ère III est bouclé. Vers l'Ère IV !",
    dialogueSuccessAr: "تفكر كمهندس هندسي وتُحس كشاعر! دائرة الحقبة الثالثة اكتملت. نحو الحقبة الرابعة!",
    dialogueFailure: "'Si tu peux tenir deux instants ensemble, tu as la vie en main.' Reviens.",
    dialogueFailureAr: "'إن استطعتَ أن تربط لحظتين معاً، فقد أمسكتَ بيد الحياة.' ارجع.",
    reward: { xp: 1600, coins: 280 },
    victoryRequirement: 9,
  },
);

// ── ÈRE IV SAGES ────────────────────────────────────────────────
SAGES.push(
  {
    id: "suleiman",
    name: "Suleiman le Magnifique",
    title: "Sultan des sultans", titleAr: "سلطان السلاطين",
    locationId: "istanbul",
    specialty: "Loi & Empire",
    personality: "majestueux et législateur",
    portrait: "ibn_rushd",
    dialogueIntro: "Je suis Suleiman Ier (1494-1566). Mon Empire s'étendait de Vienne à Bagdad, de la Crimée à l'Yémen. On m'appelle 'le Législateur' (al-Qanuni) car j'ai codifié les lois de l'Empire. 46 ans sur le trône. La Mosquée Süleymaniye que tu vois fut construite par Sinan en 7 ans.",
    dialogueIntroAr: "أنا سليمان الأول (1494-1566). امتدت إمبراطوريتي من فيينا إلى بغداد، ومن القرم إلى اليمن. يدعونني 'القانوني' لأنني قنّنتُ قوانين الإمبراطورية. 46 عاماً على العرش. مسجد السليمانية الذي تراه بناه سنان في 7 سنوات.",
    dialogueSuccess: "Mashallah ! Tu as la vision d'un sultan. Agra et l'empire moghol t'attendent.",
    dialogueSuccessAr: "ما شاء الله! لديك رؤية سلطان. أغرا والإمبراطورية المغولية تنتظرانك.",
    dialogueFailure: "Mon empire a tenu grâce à la rigueur. Reviens avec plus de sérieux.",
    dialogueFailureAr: "صمدت إمبراطوريتي بفضل الصرامة. ارجع بجدية أكبر.",
    reward: { xp: 1200, coins: 220 },
    victoryRequirement: 8,
  },
  {
    id: "akbar",
    name: "Akbar le Grand",
    title: "L'Empereur de la tolérance", titleAr: "إمبراطور التسامح",
    locationId: "agra",
    specialty: "Gouvernance & Coexistence",
    personality: "pragmatique et ouvert d'esprit",
    portrait: "al_khwarizmi",
    dialogueIntro: "Je suis Jalal ud-Din Akbar (1542-1605). Analphabète mais brillant, j'ai gouverné l'Inde en réunissant hindous, musulmans, zoroastriens et jésuites à ma cour. J'ai aboli la jizya, réformé les impôts, créé l'ère Ilahi. Le Taj Mahal que mon petit-fils Shah Jahan construira pour Mumtaz — c'est l'amour de nos Moghols crystallisé en marbre.",
    dialogueIntroAr: "أنا جلال الدين أكبر (1542-1605). أمي لكن نابغة، حكمتُ الهند بجمع الهندوس والمسلمين والزرادشتيين واليسوعيين في بلاطي. ألغيتُ الجزية وأصلحتُ الضرائب وأسستُ التقويم الإلهي. تاج محل الذي سيبنيه حفيدي شاه جهان لمُمتاز — هو محبتنا المغولية مُتبلّرةً في الرخام.",
    dialogueSuccess: "Excellente gouvernance ! Isfahan et sa philosophie profonde t'attendent.",
    dialogueSuccessAr: "حوكمة ممتازة! أصفهان وفلسفتها العميقة تنتظرانك.",
    dialogueFailure: "La tolérance s'apprend. Reviens avec un esprit plus ouvert.",
    dialogueFailureAr: "التسامح يُتعلّم. ارجع بعقل أكثر انفتاحاً.",
    reward: { xp: 1400, coins: 250 },
    victoryRequirement: 8,
  },
  {
    id: "mulla_sadra",
    name: "Mulla Sadra",
    title: "Philosophe de l'être", titleAr: "فيلسوف الوجود",
    locationId: "isfahan",
    specialty: "Philosophie islamique & Métaphysique",
    personality: "mystique et rigoureux",
    portrait: "ibn_sina",
    dialogueIntro: "Je suis Sadr ud-Din Shirazi, dit Mulla Sadra (1572-1640). J'ai passé 7 ans seul dans le désert de Kahak pour contempler l'Être. Ma 'Sagesse supérieure' (Hikmat al-Muta'aliya) est une synthèse d'Ibn Sina, Al-Suhrawardi et Ibn Arabi. Isfahan était le Bagdad du XVIIe siècle.",
    dialogueIntroAr: "أنا صدر الدين الشيرازي، ملا صدرا (1572-1640). قضيتُ 7 سنوات وحيداً في صحراء كهك للتأمل في الوجود. 'الحكمة المتعالية' تجمع ابن سينا والسهروردي وابن عربي. أصفهان كانت بغداد القرن السابع عشر.",
    dialogueSuccess: "Ton être rayonne de connaissance ! Gao et l'empire Songhaï t'attendent.",
    dialogueSuccessAr: "وجودك يشعّ بالمعرفة! غاو وإمبراطورية الصنغاي تنتظرانك.",
    dialogueFailure: "La philosophie réclame profondeur. Reviens après méditation.",
    dialogueFailureAr: "الفلسفة تتطلب عمقاً. ارجع بعد التأمل.",
    reward: { xp: 1700, coins: 290 },
    victoryRequirement: 9,
  },
  {
    id: "askia",
    name: "Askia Muhammad",
    title: "Sultan pèlerin du Songhaï", titleAr: "السلطان الحاج الصنغاوي",
    locationId: "gao",
    specialty: "Gouvernance islamique en Afrique",
    personality: "juste et réformateur",
    portrait: "ahmad_baba",
    dialogueIntro: "Je suis Askia Muhammad Ier (1443-1538). J'ai usurpé le trône de Gao — mais pour instaurer la charia et réformer l'empire Songhaï. Mon pèlerinage à La Mecque (1496-97) avec 300 000 pièces d'or fut comparable à celui de Mansa Musa. J'ai fait de Tombouctou un centre d'enseignement islamique avec 150 écoles coraniques.",
    dialogueIntroAr: "أنا أسكيا محمد الأول (1443-1538). استوليتُ على عرش غاو — لكن لإقامة الشريعة وإصلاح إمبراطورية الصنغاي. حجّي إلى مكة (1496-97) مع 300 ألف قطعة ذهب كان مماثلاً لحج مانسا موسى. جعلتُ تمبكتو مركزاً للتعليم الإسلامي بـ150 مدرسة قرآنية.",
    dialogueSuccess: "Magnifique service à l'islam africain ! Zanzibar et l'islam swahili t'appellent.",
    dialogueSuccessAr: "خدمة رائعة للإسلام الأفريقي! زنجبار والإسلام السواحيلي يناديانك.",
    dialogueFailure: "L'Afrique islamique mérite mieux que ça. Étudie et reviens.",
    dialogueFailureAr: "الإسلام الأفريقي يستحق أفضل من ذلك. ادرس وارجع.",
    reward: { xp: 2000, coins: 340 },
    victoryRequirement: 9,
  },
  {
    id: "ibn_battuta_zanzibar",
    name: "Ibn Battuta",
    title: "Le Voyageur des mondes", titleAr: "رحّالة الدنيا",
    locationId: "zanzibar",
    specialty: "Exploration & Islam mondial",
    personality: "curieux et aventurier",
    portrait: "ibn_khaldoun",
    dialogueIntro: "Je suis Ibn Battuta (1304-1368/77). 120 000 km parcourus en 30 ans — soit 3× le trajet Marco Polo. Zanzibar fut l'une de mes escales sur la côte swahili. J'ai vu l'islam à Timbuktu, Pékin, Delhi, Istanbul, au Mali — partout la oumma m'a accueilli. Ma Rihla est le miroir du monde islamique du XIVe siècle.",
    dialogueIntroAr: "أنا ابن بطوطة (1304-1368/77). 120 ألف كيلومتر في 30 عاماً — أي 3 أضعاف رحلة ماركو بولو. كانت زنجبار إحدى محطاتي على الساحل السواحيلي. رأيتُ الإسلام في تمبكتو وبكين ودلهي وإسطنبول ومالي — في كل مكان استقبلتني الأمة. رحلتي مرآة العالم الإسلامي في القرن الرابع عشر.",
    dialogueSuccess: "Walahi, tu es un vrai voyageur du savoir ! L'Ère V — La Maîtrise — t'attend.",
    dialogueSuccessAr: "والله، أنت رحّالة علم حقيقي! الحقبة الخامسة — الإتقان — تنتظرك.",
    dialogueFailure: "J'ai traversé 44 pays pour chercher le savoir. Fais un peu d'effort !",
    dialogueFailureAr: "عبرتُ 44 بلداً بحثاً عن العلم. ابذل بعض الجهد!",
    reward: { xp: 2400, coins: 400 },
    victoryRequirement: 9,
  },
);

// ── ÈRE V SAGES ────────────────────────────────────────────────
SAGES.push(
  {
    id: "imam_azhar",
    name: "Sheikh Al-Azhar",
    title: "Grand Imam — gardien du savoir", titleAr: "شيخ الأزهر — حارس العلم",
    locationId: "al_azhar_v",
    specialty: "Synthèse des sciences islamiques",
    personality: "sage millénaire",
    portrait: "ibn_khaldoun",
    dialogueIntro: "Je représente mille ans d'Al-Azhar. Fondé en 970 par les Fatimides, puis sunnitisé par Saladin, Al-Azhar a traversé Croisades, Mongols, colonisation et modernité. 500 000 étudiants du monde entier. Si tu es ici, tu as traversé toutes les ères — prouve que tu mérites le titre de Hafiz.",
    dialogueIntroAr: "أمثّل ألف عام من الأزهر. أُسِّس عام 970 على يد الفاطميين ثم أعاد صلاح الدين تسنينه. اجتاز الأزهر الحروب الصليبية والمغول والاستعمار والحداثة. 500 ألف طالب من شتى أنحاء العالم. إن كنت هنا، فقد اجتزت كل الحقب — أثبت أنك تستحق لقب الحافظ.",
    dialogueSuccess: "Subhanallah ! Tu as la sagesse d'un vrai Alim. Un seul pas te sépare du titre de Hafiz. Continue.",
    dialogueSuccessAr: "سبحان الله! لديك حكمة عالم حقيقي. خطوة واحدة تفصلك عن لقب الحافظ. واصل.",
    dialogueFailure: "Mille ans d'Al-Azhar méritent mieux. Reviens mieux préparé.",
    dialogueFailureAr: "ألف عام من الأزهر تستحق أفضل. ارجع أحسن استعداداً.",
    reward: { xp: 3000, coins: 500 },
    victoryRequirement: 9,
  },
  {
    id: "izetbegovic",
    name: "Alija Izetbegović",
    title: "Philosophe et Président", titleAr: "الفيلسوف والرئيس",
    locationId: "sarajevo",
    specialty: "Islam contemporain & Droits de l'homme",
    personality: "courageux et intellectuel",
    portrait: "ibn_rushd",
    dialogueIntro: "Je suis Alija Izetbegović (1925-2003). J'ai écrit ma 'Déclaration islamique' en prison, présidé la Bosnie pendant la guerre 1992-1995, et résisté à l'agression avec les mots autant qu'avec les armes. Mon message : l'islam est compatible avec la liberté, la démocratie et la dignité humaine. L'Europe a besoin de l'islam, et l'islam a besoin de l'Europe.",
    dialogueIntroAr: "أنا علي عزت بيغوفيتش (1925-2003). كتبتُ 'إعلاني الإسلامي' في السجن، وترأّستُ البوسنة خلال حرب 1992-1995، وقاومتُ العدوان بالكلمات كما بالسلاح. رسالتي: الإسلام متوافق مع الحرية والديمقراطية والكرامة الإنسانية. أوروبا تحتاج الإسلام، والإسلام يحتاج أوروبا.",
    dialogueSuccess: "Bravo ! Tu as la profondeur d'un penseur contemporain. Kuala Lumpur et l'islam du XXIe siècle t'attendent.",
    dialogueSuccessAr: "أحسنت! لديك عمق مفكر معاصر. كوالالمبور وإسلام القرن الحادي والعشرين ينتظرانك.",
    dialogueFailure: "Nous avons survécu à la guerre. Tu peux survivre à cet échec. Reviens.",
    dialogueFailureAr: "صمدنا في وجه الحرب. تستطيع الصمود في وجه هذا الفشل. ارجع.",
    reward: { xp: 3500, coins: 600 },
    victoryRequirement: 9,
  },
  {
    id: "hamka",
    name: "Buya Hamka",
    title: "Savant, romancier & père de l'islam moderne", titleAr: "العالم والروائي وأبو الإسلام الحديث",
    locationId: "kuala_lumpur",
    specialty: "Islam contemporain & Littérature",
    personality: "humaniste et visionnaire",
    portrait: "ibn_sina",
    dialogueIntro: "Je suis Abdul Malik Karim Amrullah, dit Hamka (1908-1981). Indonésien, autodidacte, j'ai écrit 118 livres dont le Tafsir Al-Azhar — commentaire complet du Coran en indonésien. J'ai dirigé le Conseil d'Oulémas d'Indonésie, résisté à Sukarno et Suharto. L'Asie du Sud-Est compte 250 millions de musulmans — l'islam ne vient pas seulement d'Arabie.",
    dialogueIntroAr: "أنا عبد الملك كريم أمرالله، المعروف بـ'بويا همكا' (1908-1981). إندونيسي متعلّم ذاتياً، ألّفتُ 118 كتاباً منها تفسير الأزهر — تفسير كامل للقرآن بالإندونيسية. ترأّستُ هيئة العلماء الإندونيسية وقاومتُ سوكارنو وسوهارتو. جنوب شرق آسيا فيها 250 مليون مسلم — الإسلام لا يأتي من العرب فحسب.",
    dialogueSuccess: "Alhamdulillah ! Tu es un Hafiz — gardien du savoir islamique mondial. Le Mode Hafiz t'est ouvert.",
    dialogueSuccessAr: "الحمد لله! أنت حافظ — حارس المعرفة الإسلامية العالمية. وضع الحافظ أُتيح لك.",
    dialogueFailure: "118 livres en autodidacte — et toi tu baisses les bras ? Reviens.",
    dialogueFailureAr: "118 كتاباً بتعليم ذاتي — وأنت تستسلم؟ ارجع.",
    reward: { xp: 4000, coins: 700 },
    victoryRequirement: 9,
  },
);

export function getSage(id: string): SageDef | undefined {
  return SAGES.find(s => s.id === id);
}

export function getSageForLocation(locationId: string): SageDef | undefined {
  return SAGES.find(s => s.locationId === locationId);
}
