-- ═══════════════════════════════════════════════════════════════
-- Yawmi V3 — Activation des 9 arcs narratifs
-- CONTENU À VALIDER PAR UNE PERSONNE QUALIFIÉE AVANT DIFFUSION PUBLIQUE
-- Sources : Coran & Sîra fiable. Aucun dialogue inventé dans la bouche des prophètes.
-- ═══════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────
-- ARC : IBRAHIM ﷺ
-- ─────────────────────────────────────────────────────────────
insert into stories (id, title, title_ar, arc_type, total_chapters, status, order_index)
values ('arc_ibrahim', 'Ibrahim et le Feu', 'إِبْرَاهِيمُ وَالنَّارُ', 'prophets', 8, 'published', 2)
on conflict (id) do nothing;

insert into story_chapters (story_id, chapter_number, title, narrative, vocabulary, questions, values_shown, rewards)
values (
  'arc_ibrahim', 1, 'La rupture avec les idoles',
  E'Je suis un tapis ancien, tissé dans les ateliers de Babylone. Depuis des générations, on me dépose aux pieds des statues que les hommes vénèrent — des idoles de pierre, de bois, d''argile. Les gens leur apportent offrandes et prières, comme si ces objets immobiles pouvaient entendre ou répondre.\n\nCe jour-là, un jeune homme entre dans le temple. Il s''appelle Ibrahim. Son regard balaie les statues d''un bout à l''autre de la salle avec une expression que je ne peux pas mal interpréter : il ne voit pas des dieux — il voit des pierres.\n\nLe Coran nous rapporte qu''Ibrahim avait déjà, dans sa jeunesse, interrogé les étoiles, la lune et le soleil — cherchant son Seigneur. Et à chacun, quand il disparaissait à l''horizon, il concluait : ce qui disparaît ne peut être mon Seigneur. (Sourate Al-An''am, 6:76-78)\n\nCe questionnement n''était pas la révolte d''un adolescent. C''était la quête sincère d''une âme vers la vérité. Et cette vérité, Allah lui accorda de la voir clairement : il n''est de dieu qu''Allah seul — le Tawhid.\n\nIbrahim ne cherchait pas à provoquer. Il cherchait à comprendre pourquoi son peuple adorait ce que ses propres mains avaient façonné. Le Coran lui prête une parole de défi à son père : "Prends-tu des idoles pour divinités ? Je te vois, toi et ton peuple, dans un égarement manifeste." (Sourate Al-An''am, 6:74)\n\nLa leçon du tapis : la vérité ne se hérite pas mécaniquement. Ibrahim a reçu en héritage les idoles de son peuple, mais il a osé poser la question que personne ne posait. C''est cette question sincère qui l''a mené au Tawhid — et à Allah.',
  '[{"word_ar": "تَوْحِيد", "translit": "tawhid", "definition_fr": "monothéisme, unicité d''Allah", "example": "التَّوْحِيدُ أَسَاسُ الإِسْلَامِ (le tawhid est la base de l''islam)"}]',
  '[{"id":"ib1_q1","type":"comprehension","text":"Comment Ibrahim cherchait-il son Seigneur avant de recevoir la révélation, selon le Coran (6:76-78) ?","options":[{"text":"Il priait dans le temple des idoles","correct":false},{"text":"Il observait les astres et concluait que ce qui disparaît ne peut être Dieu","correct":true},{"text":"Il consultait les prêtres babyloniens","correct":false},{"text":"Il suivait les enseignements de son père","correct":false}]},{"id":"ib1_q2","type":"vocabulary","text":"Quel mot arabe désigne l''unicité d''Allah, concept central de la foi d''Ibrahim ?","options":[{"text":"صَبْر (sabr)","correct":false},{"text":"تَوْحِيد (tawhid)","correct":true},{"text":"رُؤْيَا (ru''ya)","correct":false},{"text":"حِكْمَة (hikma)","correct":false}]},{"id":"ib1_q3","type":"reflection","text":"Ibrahim ose questionner la religion de son peuple et de sa famille. Qu''est-ce qui demande le plus de courage selon toi : suivre la tradition ou chercher la vérité soi-même ?","reflection_prompt":"Prends le temps d''y réfléchir. Le tapis t''écoute."},{"id":"ib1_q4","type":"spaced_repetition","text":"Retiens ce mot pour la suite : تَوْحِيد (tawhid) = l''unicité d''Allah.","options":[],"spaced_ref":"ib1_q2"}]',
  ARRAY['tawhid','courage','questionnement'],
  '{"xp": 50, "coins": 15}'
);

insert into story_chapters (story_id, chapter_number, title, narrative, vocabulary, questions, values_shown, rewards)
values (
  'arc_ibrahim', 2, 'Le feu qui ne brûle pas',
  E'Je suis le même tapis, mais transporté par le vent de l''histoire jusqu''au cœur du bûcher. Le roi Nimrod a rendu son verdict : Ibrahim, qui a brisé les idoles du temple et accusé la grande statue de l''avoir fait, sera jeté vivant dans les flammes.\n\nLe Coran nous rapporte que le peuple rassembla du bois pendant des jours pour construire le plus grand feu que Babylone ait jamais vu. Les prêtres bénissaient le bûcher. La foule regardait.\n\nEt Ibrahim fut lancé dans les flammes.\n\nCe que le Coran dit ensuite est l''un des versets les plus saisissants de tout le Livre : "Nous dîmes : Ô feu, sois froid et sans danger pour Ibrahim !" (Sourate Al-Anbiya, 21:69)\n\nFroid. Et sans danger.\n\nNon pas que le feu disparaisse — il continuait de brûler. Mais Allah, qui a créé le feu et lui a donné la propriété de brûler, peut lui ordonner de ne pas brûler. Ibrahim sortit des flammes indemne, sous les yeux de ceux qui l''avaient condamné.\n\nLe Coran ajoute que cette épreuve fut une défaite pour ceux qui avaient comploté contre Ibrahim. (Sourate Al-Anbiya, 21:70)\n\nJe reste sur le sol, intact. Le feu ne touche pas ce que Allah protège.\n\nLa leçon du tapis : la confiance absolue en Allah — le tawakkul — ne demande pas l''absence de danger. Ibrahim était bel et bien dans les flammes. Sa foi n''a pas annulé le danger : elle a permis à Allah d''agir. C''est cela, le tawakkul.',
  '[{"word_ar": "خَلِيل", "translit": "khalil", "definition_fr": "ami intime, bien-aimé — titre accordé à Ibrahim par Allah", "example": "وَاتَّخَذَ اللَّهُ إِبْرَاهِيمَ خَلِيلًا (Allah a pris Ibrahim pour ami intime) — Sourate An-Nisa, 4:125"}]',
  '[{"id":"ib2_q1","type":"comprehension","text":"Quel ordre Allah donna-t-il au feu quand Ibrahim y fut jeté, selon le Coran (21:69) ?","options":[{"text":"De s''éteindre immédiatement","correct":false},{"text":"D''être froid et sans danger pour Ibrahim","correct":true},{"text":"De ne pas toucher ses vêtements","correct":false},{"text":"De lui montrer une vision","correct":false}]},{"id":"ib2_q2","type":"vocabulary","text":"Quel titre le Coran accorde-t-il à Ibrahim, signifiant ''ami intime d''Allah'' ?","options":[{"text":"رَسُول (rasul)","correct":false},{"text":"نَبِيّ (nabi)","correct":false},{"text":"خَلِيل (khalil)","correct":true},{"text":"إِمَام (imam)","correct":false}]},{"id":"ib2_q3","type":"reflection","text":"Ibrahim entre dans le feu avec une confiance totale en Allah. As-tu déjà vécu une situation difficile où tu as dû faire confiance sans voir le résultat ?","reflection_prompt":"Il n''y a pas de mauvaise réponse."},{"id":"ib2_q4","type":"spaced_repetition","text":"Rappel : تَوْحِيد (tawhid) du chapitre 1. Nouveau mot : خَلِيل (khalil) = ami intime d''Allah.","options":[],"spaced_ref":"ib2_q2"}]',
  ARRAY['tawakkul','protection_divine','epreuve'],
  '{"xp": 60, "coins": 18}'
);

-- ─────────────────────────────────────────────────────────────
-- ARC : MOUSSA ﷺ
-- ─────────────────────────────────────────────────────────────
insert into stories (id, title, title_ar, arc_type, total_chapters, status, order_index)
values ('arc_moussa', 'Moussa et Pharaon', 'مُوسَى وَفِرْعَوْنُ', 'prophets', 10, 'published', 3)
on conflict (id) do nothing;

insert into story_chapters (story_id, chapter_number, title, narrative, vocabulary, questions, values_shown, rewards)
values (
  'arc_moussa', 1, 'L''enfant du fleuve',
  E'Je suis un jonc tressé, transformé en berceau. Un berceau que des mains tremblantes ont confié aux eaux du Nil, dans la nuit profonde de l''Égypte ancienne.\n\nPharaon avait décrété la mort de tous les nouveau-nés mâles des Enfants d''Israël. La peur s''était installée dans chaque foyer. Mais Allah allait montrer que Ses plans surpassent ceux des tyrans.\n\nLe Coran nous rapporte qu''Allah inspira à la mère de Moussa : "Allaite-le ; puis, lorsque tu craindras pour lui, mets-le dans le fleuve. Ne crains pas et ne t''attriste pas : Nous te le rendrons et ferons de lui l''un des envoyés." (Sourate Al-Qasas, 28:7)\n\nCette inspiration — ce wahy — n''était pas une prophétie ordinaire. C''était une promesse divine enveloppée dans une instruction. La mère de Moussa devait accomplir un acte qui semblait absurde : confier son enfant au fleuve pour le sauver. Mais Allah lui avait donné la certitude que ce fleuve ramènerait son fils.\n\nLe berceau flotta. La rivière porta l''enfant jusqu''aux rives du palais de Pharaon — le palais même de celui qui ordonnait la mort des enfants israélites. Asiya, l''épouse de Pharaon, l''aperçut et ressentit pour lui un amour immédiat. Le Coran dit qu''elle dit à Pharaon : "Il sera une consolation pour moi et pour toi. Ne le tuez pas !" (Sourate Al-Qasas, 28:9)\n\nLa leçon du tapis : l''ennemi d''un peuple a élevé, nourri et protégé celui qui serait sa propre perte. Allah utilise les moyens que nous ne pouvons pas imaginer.',
  '[{"word_ar": "وَحْي", "translit": "wahy", "definition_fr": "révélation ou inspiration divine", "example": "وَأَوْحَيْنَا إِلَى أُمِّ مُوسَى (Nous avons inspiré la mère de Moussa) — Sourate Al-Qasas, 28:7"}]',
  '[{"id":"ms1_q1","type":"comprehension","text":"Quelle promesse Allah fit-Il à la mère de Moussa quand elle le confia au Nil (28:7) ?","options":[{"text":"Que le fleuve le porterait vers une terre étrangère","correct":false},{"text":"Qu''il le lui rendrait et en ferait un envoyé","correct":true},{"text":"Que Pharaon mourrait avant de le voir","correct":false},{"text":"Qu''il serait protégé par les anges","correct":false}]},{"id":"ms1_q2","type":"vocabulary","text":"Quel mot arabe désigne la révélation ou l''inspiration divine reçue par la mère de Moussa ?","options":[{"text":"رُؤْيَا (ru''ya)","correct":false},{"text":"وَحْي (wahy)","correct":true},{"text":"دُعَاء (du''a)","correct":false},{"text":"صَلَاة (salat)","correct":false}]},{"id":"ms1_q3","type":"reflection","text":"La mère de Moussa accomplit un acte qui semblait contre toute logique pour obéir à Allah. Y a-t-il des moments où la foi demande d''agir contre notre propre peur ?","reflection_prompt":"Partage ta réflexion."},{"id":"ms1_q4","type":"spaced_repetition","text":"Retiens : وَحْي (wahy) = inspiration ou révélation divine.","options":[],"spaced_ref":"ms1_q2"}]',
  ARRAY['confiance','providence','courage_maternel'],
  '{"xp": 50, "coins": 15}'
);

insert into story_chapters (story_id, chapter_number, title, narrative, vocabulary, questions, values_shown, rewards)
values (
  'arc_moussa', 2, 'La voix du buisson ardent',
  E'Je suis tissé de fils blancs et bruns, posé sur un rocher au flanc du mont Sinaï. Le désert est silencieux. Un homme marche, conduisant ses troupeaux. C''est Moussa — des années ont passé depuis le Nil. Il vit maintenant à Madyan, loin de l''Égypte et de ses souvenirs.\n\nSoudain, il aperçoit une flamme dans un buisson. Une flamme qui brûle sans consumer le bois. Il s''en approche, intrigué.\n\nLe Coran nous rapporte que lorsqu''il fut près de la vallée sainte de Tuwa, une voix l''appela : "Ô Moussa, Je suis ton Seigneur. Ôte tes sandales, car tu es dans la vallée sacrée de Tuwa." (Sourate Ta-Ha, 20:11-12)\n\nPuis la révélation continue : Allah Se présente, ordonne à Moussa d''accomplir la prière et de Le rappeler. Il lui montre que son bâton peut devenir un serpent, que sa main peut briller d''une lumière blanche — deux signes pour la mission à venir. (Sourate Ta-Ha, 20:14-22)\n\nEt enfin la mission : "Va vers Pharaon — il a outrepassé toutes les limites." (Sourate Ta-Ha, 20:24)\n\nMoussa, un berger en exil, se retrouve investi d''une mission qui dépasse tout ce qu''il aurait pu imaginer. Le buisson ne brûlait pas seulement le bois — il brûlait la vie ordinaire de Moussa pour en faire quelque chose d''extraordinaire.\n\nLa leçon du tapis : Allah choisit Ses envoyés non parce qu''ils sont parfaits, mais parce qu''ils Lui font confiance. Moussa n''avait ni armée ni palais — juste un bâton et une foi naissante.',
  '[{"word_ar": "رِسَالَة", "translit": "risala", "definition_fr": "message, mission prophétique", "example": "بَلَّغَ الرِّسَالَةَ (il a transmis le message) — concept central en Sourate Al-Ma''ida"}]',
  '[{"id":"ms2_q1","type":"comprehension","text":"Que dit Allah à Moussa quand il approche du buisson ardent (20:11-12) ?","options":[{"text":"Il lui annonce qu''il sera roi d''Égypte","correct":false},{"text":"Il lui dit d''ôter ses sandales car il est en terre sacrée, et Se révèle comme son Seigneur","correct":true},{"text":"Il lui demande d''aller chercher de l''eau","correct":false},{"text":"Il lui annonce la mort de Pharaon","correct":false}]},{"id":"ms2_q2","type":"vocabulary","text":"Quel mot arabe désigne le message ou la mission confiée à un prophète ?","options":[{"text":"وَحْي (wahy)","correct":false},{"text":"رِسَالَة (risala)","correct":true},{"text":"حِكْمَة (hikma)","correct":false},{"text":"تَوْحِيد (tawhid)","correct":false}]},{"id":"ms2_q3","type":"reflection","text":"Moussa était berger en exil quand Allah lui confia une mission immense. Penses-tu que nos ''petits'' moments prépèrent parfois de grandes responsabilités ?","reflection_prompt":"Réfléchis librement."},{"id":"ms2_q4","type":"spaced_repetition","text":"Rappel : وَحْي (wahy) du chapitre 1. Nouveau mot : رِسَالَة (risala) = mission prophétique.","options":[],"spaced_ref":"ms2_q2"}]',
  ARRAY['vocation','mission','humilite'],
  '{"xp": 60, "coins": 18}'
);

-- ─────────────────────────────────────────────────────────────
-- ARC : MARYAM (AS)
-- ─────────────────────────────────────────────────────────────
insert into stories (id, title, title_ar, arc_type, total_chapters, status, order_index)
values ('arc_maryam', 'Maryam, la choisie', 'مَرْيَمُ الصِّدِّيقَةُ', 'prophets', 6, 'published', 4)
on conflict (id) do nothing;

insert into story_chapters (story_id, chapter_number, title, narrative, vocabulary, questions, values_shown, rewards)
values (
  'arc_maryam', 1, 'La consacrée du temple',
  E'Je suis un tapis de prière usé par des millénaires de prosternations, posé sur le sol froid du temple de Jérusalem — Bayt Al-Maqdis. Les pierres ici portent la mémoire de mille prières.\n\nUne femme arrive, enceinte et en fin de grossesse. Elle avait fait un voeu : si Allah lui accordait un enfant, elle Le consacrerait entièrement à Son service au temple. Elle ignorait encore que cet enfant serait une fille — Maryam.\n\nLe Coran rapporte sa prière : "Seigneur, je Te consacre ce qu''il y a dans mon ventre, libéré de tout attachement mondain. Accepte-le de moi, car Tu es l''Audient, l''Omniscient." (Sourate Al-Imran, 3:35)\n\nMaryam grandit dans le temple. Allah lui accorda une faveur extraordinaire : chaque fois que Zakariya — le prophète qui la gardait — entrait dans son mihrab, il trouvait auprès d''elle une nourriture qu''il n''avait pas apportée. Il lui demanda d''où cela venait. Le Coran rapporte qu''elle répondit que cela venait d''Allah — car Allah pourvoit à qui Il veut sans compter. (Sourate Al-Imran, 3:37)\n\nMaryam ne cherchait pas les honneurs. Elle cherchait Allah. Et Allah l''honora d''une façon qui dépassait toute attente humaine.\n\nLe Coran dit qu''Allah choisit Maryam et la purifia et la choisit parmi toutes les femmes du monde. (Sourate Al-Imran, 3:42)\n\nLa leçon du tapis : la dévotion sincère et discrète ne passe pas inaperçue auprès d''Allah. Maryam ne priait pas pour être remarquée — elle priait parce qu''elle aimait Allah.',
  '[{"word_ar": "قُنُوت", "translit": "qunut", "definition_fr": "dévotion obéissante, prosternation humble et sincère", "example": "كَانَتْ مِنَ الْقَانِتِينَ (elle était parmi les dévots) — Sourate Al-Imran, 3:43"}]',
  '[{"id":"mr1_q1","type":"comprehension","text":"Quelle faveur particulière Allah accordait-Il à Maryam dans son mihrab, étonnant Zakariya ?","options":[{"text":"Elle récitait le Coran sans l''avoir appris","correct":false},{"text":"Une nourriture qu''il n''avait pas apportée se trouvait auprès d''elle","correct":true},{"text":"Elle ne dormait jamais","correct":false},{"text":"Des anges priaient avec elle","correct":false}]},{"id":"mr1_q2","type":"vocabulary","text":"Quel mot arabe désigne la dévotion obéissante et la prosternation humble ?","options":[{"text":"تَوْحِيد (tawhid)","correct":false},{"text":"قُنُوت (qunut)","correct":true},{"text":"صَبْر (sabr)","correct":false},{"text":"وَحْي (wahy)","correct":false}]},{"id":"mr1_q3","type":"reflection","text":"Maryam était dévouée en secret, sans chercher à être vue. Penses-tu que nos actes d''adoration privés ont autant de valeur que ceux accomplis en groupe ?","reflection_prompt":"Il n''y a pas de mauvaise réponse."},{"id":"mr1_q4","type":"spaced_repetition","text":"Retiens : قُنُوت (qunut) = dévotion humble et sincère.","options":[],"spaced_ref":"mr1_q2"}]',
  ARRAY['devotion','sincerite','election_divine'],
  '{"xp": 50, "coins": 15}'
);

-- ─────────────────────────────────────────────────────────────
-- ARC : LA SÎRA
-- ─────────────────────────────────────────────────────────────
insert into stories (id, title, title_ar, arc_type, total_chapters, status, order_index)
values ('arc_sira', 'La Sîra — La vie du Prophète ﷺ', 'السِّيرَةُ النَّبَوِيَّةُ', 'prophets', 12, 'published', 5)
on conflict (id) do nothing;

insert into story_chapters (story_id, chapter_number, title, narrative, vocabulary, questions, values_shown, rewards)
values (
  'arc_sira', 1, 'Al-Amin — le Fidèle',
  E'Je suis un tapis de soie rouge, tissu à La Mecque il y a plus de quatorze siècles. La ville est vivante — marchands, caravanes, pèlerins qui tournent autour de la Ka''ba. Et parmi tous ces visages, il en est un que je reconnais entre mille : celui d''un jeune homme que tout le monde appelle Al-Amin — le Fidèle.\n\nLe Coran décrit son caractère avec une formule d''une densité incomparable : "Tu es certes d''une moralité magnifique." (Sourate Al-Qalam, 68:4). Cette description ne concerne pas seulement ses actes — elle concerne son être.\n\nAvant même la révélation, Muhammad ﷺ était connu de toute La Mecque comme l''homme le plus digne de confiance. Les marchands lui confiaient leurs biens. Les tribus lui soumettaient leurs litiges. Personne ne lui connaissait un mensonge ni une trahison.\n\nUn événement célèbre dans la Sîra illustre cela : lors de la reconstruction de la Ka''ba, les tribus se disputaient pour savoir qui aurait l''honneur de replacer la Pierre Noire. La tension montait. Quelqu''un proposa : "Que le premier homme qui entre dans la cour décide." Ce premier homme fut Muhammad ﷺ. Sa solution — laisser chaque tribu porter un coin du tissu ensemble — fut acceptée par tous.\n\nIl n''avait pas encore reçu la révélation. Il était simplement lui-même : juste, sage et fiable.\n\nLe Coran le présente aussi comme "uswatun hasana" — un beau modèle — pour ceux qui espèrent en Allah et au Jour Dernier. (Sourate Al-Ahzab, 33:21)\n\nLa leçon du tapis : le Prophète ﷺ ne devint pas fidèle après la révélation — il l''était avant. Allah choisit pour porter Son message quelqu''un dont le caractère était déjà la preuve vivante de Sa guidance.',
  '[{"word_ar": "أَمِين", "translit": "amin", "definition_fr": "fidèle, digne de confiance — titre du Prophète ﷺ à La Mecque", "example": "كَانَ يُدْعَى الأَمِينَ (il était appelé le Fidèle) — Sîra An-Nabawiyya"}]',
  '[{"id":"si1_q1","type":"comprehension","text":"Comment le Coran décrit-il la moralité du Prophète ﷺ dans la Sourate Al-Qalam (68:4) ?","options":[{"text":"Fort et courageux","correct":false},{"text":"D''une moralité magnifique","correct":true},{"text":"Patient et silencieux","correct":false},{"text":"Savant et sage","correct":false}]},{"id":"si1_q2","type":"vocabulary","text":"Quel surnom les habitants de La Mecque donnaient-ils au Prophète ﷺ avant même la révélation ?","options":[{"text":"النَّبِيّ (an-nabi)","correct":false},{"text":"الأَمِين (al-amin)","correct":true},{"text":"الرَّسُول (ar-rasul)","correct":false},{"text":"الصَّادِق (as-sadiq)","correct":false}]},{"id":"si1_q3","type":"reflection","text":"Muhammad ﷺ était connu pour sa droiture avant même d''être prophète. Penses-tu que notre réputation au quotidien reflète réellement qui nous sommes ?","reflection_prompt":"Réfléchis librement."},{"id":"si1_q4","type":"spaced_repetition","text":"Retiens : أَمِين (amin) = fidèle, digne de confiance.","options":[],"spaced_ref":"si1_q2"}]',
  ARRAY['integrite','confiance','modele'],
  '{"xp": 55, "coins": 16}'
);

-- ─────────────────────────────────────────────────────────────
-- ARC : LES COMPAGNONS
-- ─────────────────────────────────────────────────────────────
insert into stories (id, title, title_ar, arc_type, total_chapters, status, order_index)
values ('arc_sahaba', 'Les Compagnons du Prophète ﷺ', 'الصَّحَابَةُ الْكِرَامُ', 'companions', 10, 'published', 6)
on conflict (id) do nothing;

insert into story_chapters (story_id, chapter_number, title, narrative, vocabulary, questions, values_shown, rewards)
values (
  'arc_sahaba', 1, 'Bilal et la lumière de la foi',
  E'Je suis un tapis usé, posé sur le sol brûlant de La Mecque, sous un soleil de plomb. Autour de moi, les esclaves travaillent. Parmi eux, un homme du nom de Bilal ibn Rabah — originaire d''Abyssinie, esclave d''Umayya ibn Khalaf.\n\nBilal avait embrassé l''islam parmi les premiers croyants. Et pour cela, son maître décida de le punir publiquement, espérant lui faire renier sa foi.\n\nLes récits de la Sîra nous rapportent qu''il était allongé sur les pierres chauffées à blanc, une lourde pierre posée sur la poitrine, sous le soleil de La Mecque. Et malgré tout, il répétait un seul mot : "Ahad. Ahad." — Un. Un. Le Tawhid, l''unicité d''Allah.\n\nUn seul mot. Un seul. Mais ce mot portait tout l''univers.\n\nLe Coran honore ceux qui ont souffert pour leur foi parmi les premiers musulmans. Il dit d''eux qu''ils sont "les premiers qui ont devancé les autres — les Muhajirin et les Ansar" et qu''Allah est satisfait d''eux et qu''ils sont satisfaits de Lui. (Sourate At-Tawba, 9:100)\n\nAbu Bakr, apprenant le sort de Bilal, racheta sa liberté. Puis, lors de l''entrée triomphale à La Mecque, le Prophète ﷺ confia à Bilal l''honneur de monter sur le toit de la Ka''ba pour appeler à la prière pour la première fois.\n\nDe l''esclave torturé au premier muezzin de La Mecque.\n\nLa leçon du tapis : la foi sincère ne se mesure pas au rang social ni à la richesse. Bilal n''avait rien — sauf une certitude que rien ni personne ne pouvait lui ôter.',
  '[{"word_ar": "إِيمَان", "translit": "iman", "definition_fr": "foi, croyance intérieure ferme en Allah", "example": "الإِيمَانُ بِاللَّهِ أَسَاسُ كُلِّ شَيْءٍ (la foi en Allah est le fondement de tout)"}]',
  '[{"id":"sa1_q1","type":"comprehension","text":"Quel mot Bilal répétait-il lors de son épreuve, exprimant sa foi inébranlable ?","options":[{"text":"Allah (الله)","correct":false},{"text":"Ahad — Un (أَحَد)","correct":true},{"text":"Sabr — Patience (صَبْر)","correct":false},{"text":"Salam — Paix (سَلَام)","correct":false}]},{"id":"sa1_q2","type":"vocabulary","text":"Quel mot arabe désigne la foi intérieure et la croyance ferme en Allah ?","options":[{"text":"إِسْلَام (islam)","correct":false},{"text":"إِيمَان (iman)","correct":true},{"text":"إِحْسَان (ihsan)","correct":false},{"text":"تَقْوَى (taqwa)","correct":false}]},{"id":"sa1_q3","type":"reflection","text":"Bilal avait tout perdu sauf sa foi. Y a-t-il quelque chose dans ta propre vie que tu refuserais de perdre même sous la pression ?","reflection_prompt":"Prends le temps de réfléchir."},{"id":"sa1_q4","type":"spaced_repetition","text":"Retiens : إِيمَان (iman) = foi intérieure.","options":[],"spaced_ref":"sa1_q2"}]',
  ARRAY['foi','perseverance','dignite'],
  '{"xp": 55, "coins": 16}'
);

-- ─────────────────────────────────────────────────────────────
-- ARC : LA HIJRA
-- ─────────────────────────────────────────────────────────────
insert into stories (id, title, title_ar, arc_type, total_chapters, status, order_index)
values ('arc_hijra', 'La Hijra — La Grande Migration', 'الْهِجْرَةُ الْمُبَارَكَةُ', 'history', 5, 'published', 7)
on conflict (id) do nothing;

insert into story_chapters (story_id, chapter_number, title, narrative, vocabulary, questions, values_shown, rewards)
values (
  'arc_hijra', 1, 'La grotte de Thawr',
  E'Je suis un tapis de laine sombre, posé dans l''obscurité de la grotte de Thawr, à quelques kilomètres de La Mecque. Deux hommes se sont réfugiés ici : le Prophète Muhammad ﷺ et son compagnon Abu Bakr As-Siddiq.\n\nLes dirigeants de Quraych avaient comploté pour assassiner Muhammad ﷺ avant qu''il puisse rejoindre Médine. Une nuit, entouré de sbires de chaque tribu, ils attendaient devant sa maison. Mais Allah protège qui Il veut.\n\nLe Coran rappelle ce moment avec une précision poignante : lorsqu''ils étaient dans la grotte et qu''Abu Bakr, en entendant les poursuivants tout proches, exprima son inquiétude, le Prophète ﷺ lui dit — le Coran rapporte ses paroles : "Ne sois pas triste. Allah est avec nous." (Sourate At-Tawba, 9:40)\n\nTrois jours dans cette grotte. Les traqueurs passèrent à quelques pas. Et pourtant, ils ne les trouvèrent pas.\n\nLe tapis de la grotte — moi — a gardé le silence de ces nuits. La foi n''était pas abstraite ici : elle était concrète, mesurable en battements de cœur, en respirations retenues.\n\nAprès trois jours, le Prophète ﷺ et Abu Bakr reprirent leur route vers Médine — le début d''une nouvelle ère pour l''islam. Cette migration fut si importante qu''elle devint le point de départ du calendrier islamique.\n\nLa leçon du tapis : le tawakkul — la confiance en Allah — ne signifie pas l''absence de peur. Abu Bakr était inquiet. Mais la réponse du Prophète ﷺ était : Allah est avec nous. Et cela changeait tout.',
  '[{"word_ar": "تَوَكُّل", "translit": "tawakkul", "definition_fr": "confiance totale en Allah, s''en remettre à Lui", "example": "وَعَلَى اللَّهِ فَتَوَكَّلُوا (et faites confiance à Allah) — Sourate Al-Ma''ida, 5:23"}]',
  '[{"id":"hi1_q1","type":"comprehension","text":"Que dit le Prophète ﷺ à Abu Bakr dans la grotte, selon le Coran (9:40) ?","options":[{"text":"Prépare-toi à combattre","correct":false},{"text":"Ne sois pas triste, Allah est avec nous","correct":true},{"text":"Partons immédiatement","correct":false},{"text":"Prie et Allah nous sauvera","correct":false}]},{"id":"hi1_q2","type":"vocabulary","text":"Quel mot désigne la confiance totale en Allah et le fait de s''en remettre à Lui ?","options":[{"text":"صَبْر (sabr)","correct":false},{"text":"تَوَكُّل (tawakkul)","correct":true},{"text":"شُكْر (shukr)","correct":false},{"text":"إِيمَان (iman)","correct":false}]},{"id":"hi1_q3","type":"reflection","text":"Le Prophète ﷺ rassure Abu Bakr au moment le plus dangereux. As-tu déjà réconforté quelqu''un — ou été réconforté — dans un moment de peur ?","reflection_prompt":"Partage si tu le souhaites."},{"id":"hi1_q4","type":"spaced_repetition","text":"Retiens : تَوَكُّل (tawakkul) = confiance totale en Allah.","options":[],"spaced_ref":"hi1_q2"}]',
  ARRAY['tawakkul','amitie','hijra'],
  '{"xp": 55, "coins": 16}'
);

-- ─────────────────────────────────────────────────────────────
-- ARC : ISMAÏL ﷺ
-- ─────────────────────────────────────────────────────────────
insert into stories (id, title, title_ar, arc_type, total_chapters, status, order_index)
values ('arc_ismail', 'Ismaïl et le Sacrifice', 'إِسْمَاعِيلُ وَالذَّبْحُ', 'prophets', 4, 'published', 8)
on conflict (id) do nothing;

insert into story_chapters (story_id, chapter_number, title, narrative, vocabulary, questions, values_shown, rewards)
values (
  'arc_ismail', 1, 'La vallée de Bacca',
  E'Je suis un tapis de sable et de poussière — oui, la vallée aride entre les montagnes du Hijaz. Aucune végétation. Aucune source. Seulement le vent et le silence.\n\nIbrahim s''est arrêté ici avec Hajar et leur fils Ismaïl, encore nourrisson. Il les laisse avec peu de provisions dans cette vallée déserte — sur ordre d''Allah, dont la sagesse dépasse notre entendement.\n\nLe Coran nous donne les mots d''Ibrahim dans sa supplication : "Notre Seigneur, j''ai fait habiter une partie de ma descendance dans une vallée sans végétation, près de Ta Maison sacrée." (Sourate Ibrahim, 14:37)\n\nHajar, voyant les provisions s''épuiser, court entre les collines de Safa et Marwa à la recherche d''eau ou d''une caravane. Sept fois. Le Coran ne décrit pas cette scène directement, mais l''islam en a fait un rite du pèlerinage — la Sa''i — accompli par des millions de personnes chaque année.\n\nEt Allah répondit. De sous les pieds du petit Ismaïl, une source jaillit — Zamzam. Une source qui coule encore aujourd''hui, quatorze siècles plus tard, abreuvant les pèlerins du monde entier.\n\nLa vallée sans eau est devenue La Mecque — la ville la plus visitée de la planète.\n\nLa leçon du tapis : ce qui semble un abandon peut être le début d''une fondation. Allah ne laisse pas ceux qui Lui font confiance dans le vide.',
  '[{"word_ar": "شُكْر", "translit": "shukr", "definition_fr": "gratitude envers Allah pour Ses bienfaits", "example": "وَإِذْ تَأَذَّنَ رَبُّكُمْ لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ (si vous êtes reconnaissants, J''augmenterai vos bienfaits) — Sourate Ibrahim, 14:7"}]',
  '[{"id":"is1_q1","type":"comprehension","text":"Qu''est-ce que Zamzam selon la tradition islamique liée à l''histoire d''Ismaïl ?","options":[{"text":"Un puits creusé par Ibrahim","correct":false},{"text":"Une source miraculeuse jaillie sous les pieds d''Ismaïl","correct":true},{"text":"Un fleuve venant d''Égypte","correct":false},{"text":"Une réserve d''eau construite par les Quraysh","correct":false}]},{"id":"is1_q2","type":"vocabulary","text":"Quel mot arabe désigne la gratitude envers Allah pour Ses bienfaits ?","options":[{"text":"صَبْر (sabr)","correct":false},{"text":"شُكْر (shukr)","correct":true},{"text":"تَوْحِيد (tawhid)","correct":false},{"text":"إِيمَان (iman)","correct":false}]},{"id":"is1_q3","type":"reflection","text":"Allah a transformé une vallée aride en la ville la plus visitée du monde. As-tu déjà vu une situation difficile se transformer en quelque chose de grand ?","reflection_prompt":"Partage ta réflexion."},{"id":"is1_q4","type":"spaced_repetition","text":"Retiens : شُكْر (shukr) = gratitude envers Allah.","options":[],"spaced_ref":"is1_q2"}]',
  ARRAY['gratitude','providence','fondation'],
  '{"xp": 50, "coins": 15}'
);

-- ─────────────────────────────────────────────────────────────
-- ARC : AL-ISRA WAL-MIRAJ
-- ─────────────────────────────────────────────────────────────
insert into stories (id, title, title_ar, arc_type, total_chapters, status, order_index)
values ('arc_isra_miraj', 'Al-Isrâ wal-Miraj', 'الْإِسْرَاءُ وَالْمِعْرَاجُ', 'history', 5, 'published', 9)
on conflict (id) do nothing;

insert into story_chapters (story_id, chapter_number, title, narrative, vocabulary, questions, values_shown, rewards)
values (
  'arc_isra_miraj', 1, 'La nuit des nuits',
  E'Je suis un tapis de la Masjid al-Haram à La Mecque, posé dans la paix de la nuit. Le Prophète Muhammad ﷺ s''est endormi près de la Ka''ba dans l''espace de Hijr Ismaïl.\n\nC''est l''année de la tristesse — une période difficile : Khadija, l''épouse bien-aimée du Prophète ﷺ, est décédée. Son oncle Abu Talib aussi. Et la mission rencontre rejet et hostilité.\n\nEt dans cette nuit de tristesse, Allah offrit à Son Prophète ﷺ quelque chose d''unique dans toute l''histoire : un voyage.\n\nLe Coran ouvre la Sourate Al-Isra avec ces mots : "Gloire à Celui qui a fait voyager Son serviteur, de nuit, de la Mosquée Sacrée à la Mosquée Al-Aqsa dont Nous avons béni les alentours, afin de lui montrer certains de Nos signes." (Sourate Al-Isra, 17:1)\n\nDe La Mecque à Jérusalem — l''Isra. Puis de Jérusalem vers les cieux — le Miraj. Une seule nuit. Un voyage que nul autre n''a accompli.\n\nLe Prophète ﷺ y fut accueilli par les prophètes antérieurs. Il traversa les cieux. Il reçut l''obligation des cinq prières — un don direct, sans intermédiaire.\n\nAu retour, les incrédules de La Mecque nièrent. Certains croyants vacillèrent. Abu Bakr, lui, dit simplement : "Si c''est lui qui le dit, c''est vrai." C''est pourquoi il reçut le titre de As-Siddiq — le Véridique.\n\nLa leçon du tapis : Allah consolide la foi dans les moments de douleur. Le voyage nocturne n''arriva pas quand tout allait bien — il arriva après l''année de la tristesse.',
  '[{"word_ar": "إِسْرَاء", "translit": "isra", "definition_fr": "voyage nocturne — du nom du voyage du Prophète ﷺ de La Mecque à Jérusalem", "example": "سُبْحَانَ الَّذِي أَسْرَى (Gloire à Celui qui a fait voyager de nuit) — Sourate Al-Isra, 17:1"}]',
  '[{"id":"im1_q1","type":"comprehension","text":"De quelle mosquée à quelle mosquée s''effectue le voyage de l''Isra selon le Coran (17:1) ?","options":[{"text":"De Médine à La Mecque","correct":false},{"text":"De la Mosquée Sacrée (La Mecque) à la Mosquée Al-Aqsa (Jérusalem)","correct":true},{"text":"De Jérusalem au ciel","correct":false},{"text":"De La Mecque au Sinaï","correct":false}]},{"id":"im1_q2","type":"vocabulary","text":"Quel mot arabe désigne le voyage nocturne du Prophète ﷺ de La Mecque à Jérusalem ?","options":[{"text":"هِجْرَة (hijra)","correct":false},{"text":"إِسْرَاء (isra)","correct":true},{"text":"مِعْرَاج (miraj)","correct":false},{"text":"رِحْلَة (rihla)","correct":false}]},{"id":"im1_q3","type":"reflection","text":"Ce voyage eut lieu après une période très douloureuse pour le Prophète ﷺ. Que penses-tu du fait qu''Allah choisit parfois les moments les plus difficiles pour accorder Ses plus grands dons ?","reflection_prompt":"Réfléchis librement."},{"id":"im1_q4","type":"spaced_repetition","text":"Retiens : إِسْرَاء (isra) = voyage nocturne.","options":[],"spaced_ref":"im1_q2"}]',
  ARRAY['consolation_divine','foi','priere'],
  '{"xp": 60, "coins": 18}'
);

-- ─────────────────────────────────────────────────────────────
-- ARC : SOULEIMANE ﷺ
-- ─────────────────────────────────────────────────────────────
insert into stories (id, title, title_ar, arc_type, total_chapters, status, order_index)
values ('arc_souleimane', 'Souleimane, le Roi Sage', 'سُلَيْمَانُ الْحَكِيمُ', 'prophets', 7, 'published', 10)
on conflict (id) do nothing;

insert into story_chapters (story_id, chapter_number, title, narrative, vocabulary, questions, values_shown, rewards)
values (
  'arc_souleimane', 1, 'Le roi et la huppe',
  E'Je suis un tapis royal, tissé de fils d''or et de soie verte, déployé dans la cour de Souleimane — fils de Dawud, prophète et roi d''Israël. Son trône est immense. Ses armées comprennent des hommes, des djinns et des oiseaux.\n\nLe Coran nous rapporte que Souleimane inspectait un jour ses armées d''oiseaux et constata l''absence de la huppe — Al-Hudhud. Il déclara qu''il la châtierait sévèrement si elle ne revenait pas avec une raison valable. (Sourate An-Naml, 27:20)\n\nLa huppe revint. Et elle apporta une nouvelle extraordinaire : elle avait découvert un royaume gouverné par une femme — la reine de Saba — et ses habitants adoraient le soleil plutôt qu''Allah. (Sourate An-Naml, 27:22-24)\n\nSouleimane ne cria pas victoire. Il ne décida pas immédiatement de la guerre. Il réfléchit. Il envoya une lettre — commençant par "Bismillahi ar-Rahmani ar-Rahim" — invitant la reine à se soumettre à Allah. (Sourate An-Naml, 27:30)\n\nLe Coran nous offre ici un roi qui avait tout — pouvoir sur les djinns, le vent, les oiseaux — et qui choisissait pourtant la lettre avant l''épée.\n\nLa leçon du tapis : la sagesse — hikma — ne s''exprime pas en écrasant les autres, mais en cherchant d''abord le dialogue et la vérité. Un roi peut être juste sans être cruel.',
  '[{"word_ar": "حِكْمَة", "translit": "hikma", "definition_fr": "sagesse, jugement juste et éclairé", "example": "يُؤْتِي الْحِكْمَةَ مَن يَشَاءُ (Allah accorde la sagesse à qui Il veut) — Sourate Al-Baqara, 2:269"}]',
  '[{"id":"so1_q1","type":"comprehension","text":"Quelle information la huppe rapporta-t-elle à Souleimane de son voyage selon le Coran (27:22-24) ?","options":[{"text":"Qu''une armée ennemie approchait","correct":false},{"text":"Qu''un royaume était gouverné par une reine dont le peuple adorait le soleil","correct":true},{"text":"Qu''un trésor était caché dans le désert","correct":false},{"text":"Que les djinns se révoltaient","correct":false}]},{"id":"so1_q2","type":"vocabulary","text":"Quel mot arabe désigne la sagesse et le jugement juste ?","options":[{"text":"قُوَّة (quwwa)","correct":false},{"text":"حِكْمَة (hikma)","correct":true},{"text":"مُلْك (mulk)","correct":false},{"text":"نُور (nur)","correct":false}]},{"id":"so1_q3","type":"reflection","text":"Souleimane avait la puissance d''attaquer mais choisit d''envoyer une lettre d''abord. Dans ta vie, y a-t-il des situations où tu as choisi le dialogue plutôt que la force ?","reflection_prompt":"Il n''y a pas de mauvaise réponse."},{"id":"so1_q4","type":"spaced_repetition","text":"Retiens : حِكْمَة (hikma) = sagesse.","options":[],"spaced_ref":"so1_q2"}]',
  ARRAY['sagesse','justice','dialogue'],
  '{"xp": 55, "coins": 16}'
);
