-- ================================================================
-- Migration 007 — Chapitres supplémentaires
-- arc_ibrahim (3-5), arc_ismail (2-4), arc_isra_miraj (2-4)
-- Sources : Coran et Sîra uniquement.
-- Aucun dialogue inventé dans la bouche des prophètes.
-- ================================================================

-- ─────────────────────────────────────────────────────────────
-- ARC IBRAHIM — chapitres 3, 4, 5
-- ─────────────────────────────────────────────────────────────

insert into story_chapters (story_id, chapter_number, title, narrative, vocabulary, questions, values_shown, rewards)
values (
  'arc_ibrahim', 3, 'Le départ vers la Terre promise',
  E'Je suis un tapis de voyage — tissé en Perse, usé par les pistes du désert. J''ai traversé bien des pays, mais aucun voyage ne m''a autant marqué que celui d''Ibrahim quittant Babylone.\n\nAprès l''épreuve du feu, les habitants de Babylone avaient été témoins d''un miracle qu''ils ne pouvaient nier. Pourtant, beaucoup refusèrent de croire. Le Coran nous dit : "Nous le sauvâmes, lui et Lot, vers la terre que Nous avions bénie pour les mondes." (Sourate Al-Anbiya, 21:71)\n\nIbrahim part. Avec lui, sa femme Sarah et son neveu Lot. Il laisse derrière lui sa famille, son pays, tout ce qu''il connaît — uniquement parce qu''Allah le lui ordonne. Cette migration volontaire pour Allah s''appelle la hijra.\n\nLe Coran nous décrit Ibrahim dans une supplication sincère avant son départ : "Mon Seigneur, fais-moi entrer d''une entrée de vérité et fais-moi sortir d''une sortie de vérité, et accorde-moi de Ta part une puissance salvatrice." (Sourate Al-Isra, 17:80)\n\nCe n''est pas une fuite. C''est un départ vers Allah. Ibrahim ne sait pas encore ce que la Terre promise lui réserve — mais il sait Qui l''y envoie.\n\nLe tapis comprend, dans ses fils tissés de voyages, que l''exil volontaire pour Allah n''est pas une perte. C''est le début de quelque chose de plus grand que ce qu''on laisse.\n\nLa leçon du tapis : Ibrahim n''a pas cherché une nouvelle patrie. Il a cherché la satisfaction d''Allah — et la patrie est venue en plus.',
  '[{"word_ar": "هِجْرَة", "translit": "hijra", "definition_fr": "migration / départ volontaire pour Allah", "example": "وَمَن يُهَاجِرْ فِي سَبِيلِ اللَّهِ يَجِدْ فِي الْأَرْضِ مُرَاغَمًا كَثِيرًا (celui qui migre dans le chemin d''Allah trouvera sur terre de nombreuses ressources) — Sourate An-Nisa, 4:100"}]',
  '[{"id":"ib3_q1","type":"comprehension","text":"Selon le Coran (21:71), vers où Allah sauva-t-Il Ibrahim et Lot après l''épreuve du feu ?","options":[{"text":"Vers l''Égypte","correct":false},{"text":"Vers la terre que Nous avions bénie pour les mondes","correct":true},{"text":"Vers La Mecque","correct":false},{"text":"Vers le Sinaï","correct":false}]},{"id":"ib3_q2","type":"vocabulary","text":"Quel mot arabe désigne la migration volontaire pour Allah ?","options":[{"text":"سَفَر (safar)","correct":false},{"text":"هِجْرَة (hijra)","correct":true},{"text":"رِحْلَة (rihla)","correct":false},{"text":"خُرُوج (khuruj)","correct":false}]},{"id":"ib3_q3","type":"reflection","text":"Ibrahim quitte tout ce qu''il connaît pour obéir à Allah. Y a-t-il des choses dans ta vie que tu renoncerais à garder par amour d''Allah ?","reflection_prompt":"Le tapis t''écoute sans jugement."},{"id":"ib3_q4","type":"spaced_repetition","text":"Rappel des chapitres précédents : تَوْحِيد (tawhid) et خَلِيل (khalil). Nouveau mot : هِجْرَة (hijra) = migration pour Allah.","options":[],"spaced_ref":"ib3_q2"}]',
  ARRAY['detachement','obeissance','confiance'],
  '{"xp": 55, "coins": 16}'
),
(
  'arc_ibrahim', 4, 'Le songe du sacrifice',
  E'Je suis un tapis de la vallée de Mina, non loin de La Mecque. Les pierres y sont blanches, le ciel immense. Je ne savais pas encore que ce lieu deviendrait l''un des plus sacrés de la terre.\n\nIsmaïl avait grandi. La vallée de Bacca — que l''on appellera La Mecque — était devenue son foyer. Ibrahim venait lui rendre visite.\n\nEt lors d''une de ces visites, Ibrahim reçut un songe. Le Coran nous rapporte sa parole à son fils — non pas comme un ordre brutal, mais comme une consultation pleine de tendresse : "Mon fils, je vois en songe que je t''immole. Vois ce que tu en penses." (Sourate As-Saffat, 37:102)\n\nNotez : Ibrahim ne cache pas le songe à Ismaïl. Il lui en parle, lui demande son avis — parce qu''Ismaïl aussi est concerné dans cette épreuve. Le Coran ne nous rapporte pas qu''Ibrahim lui dit "je vais le faire" mais "vois ce que tu en penses".\n\nEt la réponse d''Ismaïl — que le Coran nous transmet — est l''une des paroles les plus saisissantes des Écritures : "Ô mon père, fais ce qu''on t''ordonne ! Tu me trouveras, si Allah le veut, parmi les endurants." (Sourate As-Saffat, 37:102)\n\nDeux hommes. Un père et un fils. Tous deux soumis à Allah.\n\nLa leçon du tapis : le vrai test n''est pas d''obéir quand c''est facile. Ibrahim et Ismaïl obéirent quand c''était le plus difficile.',
  '[{"word_ar": "صَبْر", "translit": "sabr", "definition_fr": "patience, endurance dans l''épreuve", "example": "إِنَّ اللَّهَ مَعَ الصَّابِرِينَ (Allah est avec ceux qui endurent) — Sourate Al-Baqara, 2:153"}]',
  '[{"id":"ib4_q1","type":"comprehension","text":"Comment Ibrahim annonce-t-il à Ismaïl le songe du sacrifice, selon le Coran (37:102) ?","options":[{"text":"Il lui ordonne sans explication","correct":false},{"text":"Il lui demande son avis : \"Vois ce que tu en penses\"","correct":true},{"text":"Il l''endort et procède sans le lui dire","correct":false},{"text":"Il attend que des témoins soient présents","correct":false}]},{"id":"ib4_q2","type":"vocabulary","text":"Quel mot arabe désigne la patience et l''endurance dans l''épreuve ?","options":[{"text":"شُكْر (shukr)","correct":false},{"text":"تَوَاضُع (tawadu)","correct":false},{"text":"صَبْر (sabr)","correct":true},{"text":"حِكْمَة (hikma)","correct":false}]},{"id":"ib4_q3","type":"reflection","text":"Ismaïl accepte librement l''épreuve et promet d''endurer. Qu''est-ce que cela t''apprend sur le sens du mot \"islam\" (soumission à Allah) ?","reflection_prompt":"Réfléchis au lien entre islam et la réponse d''Ismaïl."},{"id":"ib4_q4","type":"spaced_repetition","text":"Retiens : صَبْر (sabr) = patience dans l''épreuve. C''est ce qu''Ismaïl promet à son père.","options":[],"spaced_ref":"ib4_q2"}]',
  ARRAY['soumission','patience','epreuve_ultime'],
  '{"xp": 65, "coins": 20}'
),
(
  'arc_ibrahim', 5, 'La Ka''ba — la Maison d''Allah',
  E'Je suis un tapis de la vallée de Bacca — cette même vallée que Hajar a traversée en courant, là où Zamzam a jailli. Maintenant, des années plus tard, Ibrahim et Ismaïl construisent quelque chose sur cette terre bénie.\n\nLe Coran nous raconte cette scène dans des mots simples mais immenses : "Et voilà qu''Ibrahim élevait les fondations de la Maison avec Ismaïl : Notre Seigneur, accepte de nous. Tu es, en vérité, l''Audient, l''Omniscient." (Sourate Al-Baqara, 2:127)\n\nIls construisent. Et en construisant, ils supplient — comme si l''acte le plus grand peut toujours ne pas être accepté sans la grâce d''Allah.\n\nCette Maison — la Ka''ba — n''est pas une statue. Elle n''a pas de visage, pas de forme divine. C''est un lieu désigné par Allah comme centre de direction pour le monde entier. Quand les musulmans du monde entier prient, ils se tournent vers elle — pas pour l''adorer, mais parce qu''Allah l''a choisie comme point d''unité.\n\nIbrahim supplie Allah d''en faire un lieu de paix, et d''envoyer à cette communauté un prophète venu d''elle. (Sourate Al-Baqara, 2:129). Cette supplication fut exaucée des siècles plus tard — avec la naissance de Muhammad ﷺ, descendant d''Ismaïl.\n\nLa leçon du tapis : Ibrahim a construit une maison pour Allah, en suppliant Allah de l''accepter. Même nos meilleurs actes ont besoin de Sa grâce.',
  '[{"word_ar": "قِبْلَة", "translit": "qibla", "definition_fr": "direction vers laquelle on se tourne pour prier", "example": "فَوَلِّ وَجْهَكَ شَطْرَ الْمَسْجِدِ الْحَرَامِ (tourne ton visage vers la Mosquée Sacrée) — Sourate Al-Baqara, 2:144"}]',
  '[{"id":"ib5_q1","type":"comprehension","text":"Selon le Coran (2:127), qui bâtit les fondations de la Ka''ba ?","options":[{"text":"Ibrahim seul","correct":false},{"text":"Ibrahim et Ismaïl ensemble","correct":true},{"text":"Ibrahim et Hajar","correct":false},{"text":"Les anges sous la direction d''Ibrahim","correct":false}]},{"id":"ib5_q2","type":"vocabulary","text":"Quel mot arabe désigne la direction vers laquelle les musulmans se tournent pour prier ?","options":[{"text":"صَلَاة (salah)","correct":false},{"text":"مَسْجِد (masjid)","correct":false},{"text":"قِبْلَة (qibla)","correct":true},{"text":"كَعْبَة (ka''ba)","correct":false}]},{"id":"ib5_q3","type":"reflection","text":"Ibrahim et Ismaïl suplient Allah d''accepter leur travail même en le faisant. Penses-tu à demander à Allah d''accepter tes bonnes actions quand tu les fais ?","reflection_prompt":"Réfléchis à ta pratique personnelle."},{"id":"ib5_q4","type":"spaced_repetition","text":"Récapitulatif Ibrahim : تَوْحِيد · خَلِيل · هِجْرَة · صَبْر · قِبْلَة. Cinq mots, cinq chapitres.","options":[],"spaced_ref":"ib5_q2"}]',
  ARRAY['tawhid','unité_oumma','supplication'],
  '{"xp": 70, "coins": 22}'
);

-- ─────────────────────────────────────────────────────────────
-- ARC ISMAIL — chapitres 2, 3, 4
-- ─────────────────────────────────────────────────────────────

insert into story_chapters (story_id, chapter_number, title, narrative, vocabulary, questions, values_shown, rewards)
values (
  'arc_ismail', 2, 'La Sa''i — sept allers-retours',
  E'Je suis la poussière entre Safa et Marwa — deux collines qui dominent la vallée aride de Bacca. Personne ne me foule encore, car cette vallée est vide. Vide de tout, sauf d''une femme et d''un nourrisson.\n\nHajar court. Elle grimpe sur Safa, scrute l''horizon. Rien. Elle descend, court jusqu''à Marwa, cherche. Rien. Elle recommence. Une fois, deux fois, sept fois.\n\nLe Coran ne décrit pas cette scène dans le détail — mais il lui donne un statut : la Sa''i, cet aller-retour entre Safa et Marwa, est devenu l''un des rites obligatoires du pèlerinage. Allah lui-même dit dans le Coran : "Safa et Marwa sont parmi les symbols d''Allah. Quiconque fait le pèlerinage à la Maison ou la Omra, il ne commet aucun péché à les faire le tour." (Sourate Al-Baqara, 2:158)\n\nSa persévérance — sept courses, sans garantie de résultat visible — a été consacrée. Ses pas répétés dans la poussière sont devenus des pas que des millions d''humains répèteront jusqu''au Jour du Jugement.\n\nEt à la fin du septième aller-retour, l''eau surgit. Zamzam. Non pas parce que Hajar avait trouvé la bonne technique. Mais parce qu''Allah attendait ce moment précis pour répondre.\n\nLa leçon du tapis : la persévérance sans résultat visible n''est pas du temps perdu. C''est de la foi en acte.',
  '[{"word_ar": "صِرَاط", "translit": "sirat", "definition_fr": "chemin, voie droite — le chemin vers Allah", "example": "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ (guide-nous sur le chemin droit) — Sourate Al-Fatiha, 1:6"}]',
  '[{"id":"is2_q1","type":"comprehension","text":"Quel rite islamique du pèlerinage est directement lié à la course de Hajar entre Safa et Marwa ?","options":[{"text":"Le tawaf autour de la Ka''ba","correct":false},{"text":"La Sa''i — sept allers-retours entre Safa et Marwa","correct":true},{"text":"La lapidation à Mina","correct":false},{"text":"La station à Arafat","correct":false}]},{"id":"is2_q2","type":"vocabulary","text":"Quel mot arabe signifie le ''chemin droit'' vers Allah, mentionné dans la Fatiha ?","options":[{"text":"صِرَاط (sirat)","correct":true},{"text":"طَرِيق (tariq)","correct":false},{"text":"سَبِيل (sabil)","correct":false},{"text":"مَنْهَج (manhaj)","correct":false}]},{"id":"is2_q3","type":"reflection","text":"Hajar court sans savoir que chacun de ses pas deviendra un rite pour des millions de personnes. Crois-tu que nos actes sincères ont des conséquences que nous ne pouvons pas voir ?","reflection_prompt":"Prends le temps d''y réfléchir."},{"id":"is2_q4","type":"spaced_repetition","text":"Rappel : شُكْر (shukr) du chapitre 1. Nouveau mot : صِرَاط (sirat) = chemin droit.","options":[],"spaced_ref":"is2_q2"}]',
  ARRAY['perseverance','confiance','foi_en_acte'],
  '{"xp": 55, "coins": 16}'
),
(
  'arc_ismail', 3, 'Ismaïl le soumis',
  E'Je suis le sol de Mina — cette vallée près de La Mecque, là où Ibrahim amena son fils pour l''épreuve suprême. La même pierre blanche. Le même silence.\n\nIsmaïl avait accepté. Ce qu''il avait promis à son père — "tu me trouveras parmi les endurants" — il le tint.\n\nIbrahim se prépare à accomplir ce que le songe lui avait montré. Et au moment de l''acte, le Coran nous dit : "Nous l''appelâmes : ''Ibrahim ! Tu as confirmé le songe.'' Ainsi récompensons-Nous les bienfaisants." (Sourate As-Saffat, 37:104-105)\n\nAllah intervint avant que le sacrifice s''accomplisse. Ibrahim avait passé l''épreuve — non pas en réalisant l''acte jusqu''au bout, mais en ayant la volonté sincère de le faire. La sincérité de l''intime comptait plus que l''acte lui-même.\n\nEt à la place d''Ismaïl, un bélier immense descendit du ciel. (Sourate As-Saffat, 37:107)\n\nCe remplacement est la source de l''Aïd al-Adha — la fête du sacrifice. Chaque année, des millions de musulmans commémorent non pas le sacrifice d''un fils, mais la soumission totale de deux êtres humains à Allah.\n\nIsmaïl n''est pas seulement le fils du sacrifice. Il est le prototype du croyant qui accepte — et dont la soumission est rachetée par la grâce d''Allah.\n\nLa leçon du tapis : Allah ne veut pas notre sang. Il veut notre cœur.',
  '[{"word_ar": "فِدَاء", "translit": "fida", "definition_fr": "rançon, ce qui est donné en échange / rachat", "example": "وَفَدَيْنَاهُ بِذِبْحٍ عَظِيمٍ (et Nous le rachetâmes par un immense sacrifice) — Sourate As-Saffat, 37:107"}]',
  '[{"id":"is3_q1","type":"comprehension","text":"Comment Allah interrompt-Il l''épreuve du sacrifice selon le Coran (37:104-107) ?","options":[{"text":"En envoyant un ange arrêter le bras d''Ibrahim","correct":false},{"text":"En appelant Ibrahim et en envoyant un bélier à la place","correct":true},{"text":"En faisant apparaître Ismaïl invincible","correct":false},{"text":"En envoyant une révélation écrite","correct":false}]},{"id":"is3_q2","type":"vocabulary","text":"Quel mot arabe désigne le rachat — donner quelque chose à la place de quelqu''un d''autre ?","options":[{"text":"هَدِيَّة (hadiya)","correct":false},{"text":"فِدَاء (fida)","correct":true},{"text":"عَطَاء (ata)","correct":false},{"text":"قُرْبَان (qurban)","correct":false}]},{"id":"is3_q3","type":"reflection","text":"Allah dit à Ibrahim : \"Tu as confirmé le songe.\" Cela signifie que l''acte accompli est la sincérité intérieure, pas l''acte lui-même. Comment cette idée change-t-elle ta façon de voir tes propres actes d''adoration ?","reflection_prompt":"Réfléchis à l''intention (niyya) derrière tes actes."},{"id":"is3_q4","type":"spaced_repetition","text":"Mots clés de l''arc Ismaïl : شُكْر · صِرَاط · فِدَاء. Ismaïl = شُكْر (gratitude), Sa''i = صِرَاط (chemin), sacrifice = فِدَاء (rachat).","options":[],"spaced_ref":"is3_q2"}]',
  ARRAY['soumission','sincerite','grace_divine'],
  '{"xp": 65, "coins": 20}'
),
(
  'arc_ismail', 4, 'Le prophète de la langue arabe',
  E'Je suis un tapis tissé en Arabie — mes fils sont de laine de chameau et de fibres du désert. Ismaïl a grandi dans cette vallée, et avec lui a grandi une langue.\n\nIsmaïl ne reste pas un enfant de l''épreuve. Le Coran lui donne un titre complet et distinct : il est un prophète et un messager, envoyé à son peuple. "Et mentionne dans le Livre Ismaïl. Il était véridique dans ses promesses, et il était un messager, un prophète." (Sourate Maryam, 19:54)\n\nVéridique dans ses promesses — صَادِق الوَعْد. Ces trois mots résument Ismaïl. Quand il promit à son père d''endurer, il endura. Quand il construisit la Ka''ba avec Ibrahim, il construisit jusqu''au bout. Quand il appela son peuple à l''adoration d''Allah, il n''abandonna pas.\n\nSes descendants formeront les tribus arabes du Hijaz. Et des siècles plus tard, de sa descendance naîtra Muhammad ﷺ — l''accomplissement de la supplication d''Ibrahim.\n\nIsmaïl est le lien entre la Ka''ba et le Prophète ﷺ. Entre la pierre et la révélation finale. Entre le sacrifice et la miséricorde.\n\nLa leçon du tapis : Ismaïl a honoré chaque parole qu''il a donnée. Sa fidélité à ses promesses — envers son père, envers Allah, envers son peuple — est le fil conducteur de toute sa vie.',
  '[{"word_ar": "صِدْق", "translit": "sidq", "definition_fr": "véridicité, honnêteté, fidélité à la vérité", "example": "وَكَانَ صَادِقَ الْوَعْدِ (il était véridique dans ses promesses) — Sourate Maryam, 19:54"}]',
  '[{"id":"is4_q1","type":"comprehension","text":"Quels deux titres le Coran accorde-t-il à Ismaïl dans la Sourate Maryam (19:54) ?","options":[{"text":"Khalil et Siddiq","correct":false},{"text":"Messager et Prophète","correct":true},{"text":"Nabi et Rasul (synonymes dans ce verset)","correct":false},{"text":"Imam et Khalifa","correct":false}]},{"id":"is4_q2","type":"vocabulary","text":"Quel mot arabe signifie la véridicité, l''honnêteté totale ?","options":[{"text":"إِخْلَاص (ikhlas)","correct":false},{"text":"صِدْق (sidq)","correct":true},{"text":"وَفَاء (wafa)","correct":false},{"text":"أَمَانَة (amana)","correct":false}]},{"id":"is4_q3","type":"reflection","text":"Le Coran décrit Ismaïl comme ''véridique dans ses promesses''. Réfléchis à ta propre relation aux promesses que tu fais — à Allah, à ta famille, à toi-même.","reflection_prompt":"Prends le temps d''être honnête avec toi-même."},{"id":"is4_q4","type":"spaced_repetition","text":"Bilan arc Ismaïl : شُكْر (gratitude) · صِرَاط (chemin) · فِدَاء (rachat) · صِدْق (véridicité). Quatre mots, quatre leçons.","options":[],"spaced_ref":"is4_q2"}]',
  ARRAY['veridicite','prophetie','heritage_ibrahim'],
  '{"xp": 60, "coins": 18}'
);

-- ─────────────────────────────────────────────────────────────
-- ARC ISRA WAL-MIRAJ — chapitres 2, 3, 4
-- ─────────────────────────────────────────────────────────────

insert into story_chapters (story_id, chapter_number, title, narrative, vocabulary, questions, values_shown, rewards)
values (
  'arc_isra_miraj', 2, 'Le Miraj — l''ascension vers les cieux',
  E'Je suis un tapis suspendu entre ciel et terre — tissé de lumière, si le tapis pouvait être fait de lumière. Cette nuit-là, après le voyage de La Mecque à Jérusalem, le voyage ne s''est pas arrêté.\n\nDe Jérusalem, le Prophète ﷺ fut élevé vers les cieux. Le Coran évoque cette ascension dans la Sourate An-Najm : "Alors qu''il se trouvait à l''horizon supérieur, il s''approcha et descendit, se trouvant à deux portées d''arc ou plus près encore." (Sourate An-Najm, 53:7-9)\n\nDans les récits authentiques rapportés par Al-Bukhari et Muslim, le Prophète ﷺ traverse les sept cieux. À chaque ciel, il rencontre un prophète. Adam dans le premier. Yahya et Issa dans le second. Youssouf dans le troisième. Idris dans le quatrième. Haroun dans le cinquième. Moussa dans le sixième. Ibrahim dans le septième.\n\nChaque rencontre est une chaîne — une lignée de messagers envoyés par le même Allah, portant le même message fondamental.\n\nAu-delà du dernier ciel, le Prophète ﷺ atteint Sidrat al-Muntaha — le Jujubier de la limite ultime — au-delà duquel nul ne peut aller. (Sourate An-Najm, 53:14)\n\nLa leçon du tapis : le Prophète ﷺ ne part pas seul dans ce voyage. Il est précédé par tous les prophètes — et les rencontre un à un. L''islam n''est pas une rupture avec l''histoire divine. C''est son accomplissement.',
  '[{"word_ar": "مِعْرَاج", "translit": "miraj", "definition_fr": "ascension céleste — le voyage du Prophète ﷺ vers les cieux", "example": "سُبْحَانَ الَّذِي أَسْرَى — et le Miraj est la suite de ce voyage vers les cieux"}]',
  '[{"id":"im2_q1","type":"comprehension","text":"Selon les récits authentiques, quels prophètes le Prophète ﷺ rencontre-t-il lors de l''ascension ?","options":[{"text":"Uniquement Ibrahim et Moussa","correct":false},{"text":"Adam, Yahya, Issa, Youssouf, Idris, Haroun, Moussa, Ibrahim — un à chaque ciel","correct":true},{"text":"Les anges uniquement","correct":false},{"text":"Les compagnons décédés","correct":false}]},{"id":"im2_q2","type":"vocabulary","text":"Quel mot arabe désigne spécifiquement l''ascension céleste du Prophète ﷺ vers les cieux ?","options":[{"text":"إِسْرَاء (isra)","correct":false},{"text":"مِعْرَاج (miraj)","correct":true},{"text":"رِحْلَة (rihla)","correct":false},{"text":"رُؤْيَا (ru''ya)","correct":false}]},{"id":"im2_q3","type":"reflection","text":"Le Prophète ﷺ rencontre tous les prophètes lors de son ascension. Qu''est-ce que cela t''apprend sur le lien entre l''islam et les religions antérieures ?","reflection_prompt":"Réfléchis à la notion de ''chaîne prophétique''."},{"id":"im2_q4","type":"spaced_repetition","text":"Rappel : إِسْرَاء (isra) = voyage nocturne horizontal. Nouveau : مِعْرَاج (miraj) = ascension verticale.","options":[],"spaced_ref":"im2_q2"}]',
  ARRAY['prophetie','unite_des_prophetes','grandeur_divine'],
  '{"xp": 65, "coins": 20}'
),
(
  'arc_isra_miraj', 3, 'Le don des cinq prières',
  E'Je suis un tapis suspendu entre deux obligations — celle de cent, puis de cinquante, puis de cinq. Je témoigne de la négociation la plus belle de l''histoire.\n\nLors du Miraj, le Prophète ﷺ reçut l''obligation de la prière. Dans les récits authentiques rapportés par Al-Bukhari et Muslim, la prière fut d''abord prescrite à cinquante fois par jour.\n\nEn redescendant à travers les cieux, Moussa — que la paix soit sur lui — interpella le Prophète ﷺ : "Ma communauté a essayé avec moins que cela et n''a pas pu tenir. Retourne vers ton Seigneur et demande une réduction."\n\nLe Prophète ﷺ retourna plusieurs fois. Chaque fois, Allah réduisit. Jusqu''à cinq prières.\n\nMoussa dit encore : "Retourne, c''est encore trop." Mais le Prophète ﷺ répondit qu''il avait déjà demandé jusqu''à avoir honte de continuer.\n\nEt Allah dit : "Ces cinq prières sont prescrites et elles valent dans Ma récompense comme cinquante." (Rapporté dans les deux Sahihs)\n\nCinq en acte. Cinquante en valeur. Un cadeau enveloppé dans la miséricorde.\n\nLe Coran ne décrit pas le détail de cette négociation — mais il désigne la prière comme un pilier, une obligation, un lien direct entre le croyant et Allah, sans intermédiaire.\n\nLa leçon du tapis : la prière n''est pas une contrainte imposée du dehors. Elle est un cadeau offert lors du voyage le plus extraordinaire de l''humanité.',
  '[{"word_ar": "صَلَاة", "translit": "salah", "definition_fr": "la prière — lien direct entre le serviteur et Allah", "example": "إِنَّ الصَّلَاةَ كَانَتْ عَلَى الْمُؤْمِنِينَ كِتَابًا مَوْقُوتًا (la prière est une obligation à des temps prescrits pour les croyants) — Sourate An-Nisa, 4:103"}]',
  '[{"id":"im3_q1","type":"comprehension","text":"Combien de prières furent prescrites initialement lors du Miraj selon les récits authentiques ?","options":[{"text":"Cinq","correct":false},{"text":"Dix","correct":false},{"text":"Cinquante","correct":true},{"text":"Cent","correct":false}]},{"id":"im3_q2","type":"vocabulary","text":"Quel mot arabe désigne la prière islamique — le lien direct entre le croyant et Allah ?","options":[{"text":"دُعَاء (du''a)","correct":false},{"text":"صَلَاة (salah)","correct":true},{"text":"ذِكْر (dhikr)","correct":false},{"text":"عِبَادَة (ibada)","correct":false}]},{"id":"im3_q3","type":"reflection","text":"La prière fut donnée lors du voyage le plus extraordinaire de l''histoire — pas par une révélation ordinaire, mais face à face. Comment cela change-t-il ta façon de voir tes prières quotidiennes ?","reflection_prompt":"Prends le temps d''y réfléchir avant de répondre."},{"id":"im3_q4","type":"spaced_repetition","text":"Bilan Miraj : إِسْرَاء · مِعْرَاج · صَلَاة. Le voyage nocturne nous a donné la prière.","options":[],"spaced_ref":"im3_q2"}]',
  ARRAY['priere','misericorde','don_divin'],
  '{"xp": 65, "coins": 20}'
),
(
  'arc_isra_miraj', 4, 'Abu Bakr As-Siddiq — la foi sans preuve',
  E'Je suis un tapis de la maison d''Abu Bakr à La Mecque. J''ai entendu les rires des incrédules ce matin-là. J''ai entendu aussi la réponse de cet homme debout.\n\nLorsque le Prophète ﷺ raconta son voyage nocturne à La Mecque, les réactions furent immédiates. Certains compagnons vacillèrent. Les chefs qurayshites ricanèrent : un voyage à Jérusalem et retour en une nuit ? Impossible.\n\nIls coururent trouver Abu Bakr pour qu''il soit ébranlé lui aussi. Et Abu Bakr — que la paix soit sur lui — posa une seule question : "Est-ce lui qui vous a dit cela ?"\n\n"Oui."\n\n"Alors je le crois."\n\nIl ajouta — selon les récits : "Je le crois dans des choses plus grandes encore : la révélation qui descend du ciel."\n\nC''est ce jour-là, dit-on, qu''il reçut de la bouche même du Prophète ﷺ le titre d''As-Siddiq — le Véridique, celui qui confirme d''emblée.\n\nLe Coran évoque ceux qui croient "bil ghayb" — en ce qui est invisible. (Sourate Al-Baqara, 2:3) Abu Bakr est l''exemple parfait de cette foi : non pas aveugle, mais ancrée dans la confiance qu''il a construite à force de connaître le Prophète ﷺ.\n\nLa leçon du tapis : la vraie foi n''est pas crédulité. C''est la confiance que l''on a bâtie, acte par acte, jour après jour, dans la véridicité de celui qui parle.',
  '[{"word_ar": "غَيْب", "translit": "ghayb", "definition_fr": "l''invisible, le monde caché — ce qui dépasse les sens humains", "example": "الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ (ceux qui croient en l''invisible) — Sourate Al-Baqara, 2:3"}]',
  '[{"id":"im4_q1","type":"comprehension","text":"Quel titre le Prophète ﷺ donna-t-il à Abu Bakr après sa réaction au récit du voyage nocturne ?","options":[{"text":"Al-Faruq (celui qui distingue)","correct":false},{"text":"As-Siddiq (le Véridique, celui qui confirme)","correct":true},{"text":"Al-Amin (le fiable)","correct":false},{"text":"Dhul-Nurayn (celui aux deux lumières)","correct":false}]},{"id":"im4_q2","type":"vocabulary","text":"Quel mot arabe désigne l''invisible — ce qui dépasse les sens humains mais auquel le croyant croit ?","options":[{"text":"أَخِرَة (akhira)","correct":false},{"text":"رُوح (ruh)","correct":false},{"text":"غَيْب (ghayb)","correct":true},{"text":"بَاطِن (batin)","correct":false}]},{"id":"im4_q3","type":"reflection","text":"Abu Bakr croit sans hésiter, non par naïveté, mais par confiance construite. Quelle est la différence entre confiance aveugle et foi ancrée dans la connaissance ?","reflection_prompt":"Réfléchis à ce que ''croire'' signifie vraiment pour toi."},{"id":"im4_q4","type":"spaced_repetition","text":"Bilan arc Al-Isra wal-Miraj : إِسْرَاء · مِعْرَاج · صَلَاة · غَيْب. La foi en l''invisible est le fil conducteur.","options":[],"spaced_ref":"im4_q2"}]',
  ARRAY['foi','confiance','temoignage'],
  '{"xp": 60, "coins": 18}'
);
